import type { DocumentTemplateDefinition } from "./document-engine";

const identityFields = [
  { key: "applicantLegalName", label: "Applicant legal name", source: "LEGAL_ENTITY", required: true },
  { key: "institutionName", label: "Proposed institution name", source: "INSTITUTION_PROFILE", required: true },
  { key: "entityJurisdiction", label: "Entity jurisdiction", source: "LEGAL_ENTITY", required: true },
  { key: "formationDate", label: "Formation date", source: "LEGAL_ENTITY", required: true, externallyVerified: true },
  { key: "entityId", label: "Entity identifier", source: "LEGAL_ENTITY", required: true, externallyVerified: true },
] as const;

export const universityDocumentTemplates: DocumentTemplateDefinition[] = [
  {
    id: "thecb-certificate-authority-master",
    name: "Texas Certificate of Authority Master Application Packet",
    category: "REGULATORY_APPLICATION",
    classification: "REGULATORY",
    fields: [
      ...identityFields,
      { key: "governingBoard", label: "Governing board roster", source: "GOVERNANCE", required: true },
      { key: "chiefExecutive", label: "Chief executive", source: "GOVERNANCE", required: true },
      { key: "chiefAcademicOfficer", label: "Chief academic officer", source: "GOVERNANCE", required: true, externallyVerified: true },
      { key: "mission", label: "Institutional mission", source: "INSTITUTION_PROFILE", required: true },
      { key: "financialCapacity", label: "Financial capacity evidence", source: "FINANCE", required: true, externallyVerified: true, sensitive: true },
      { key: "suretyInstrument", label: "Surety instrument", source: "EVIDENCE", required: true, externallyVerified: true, sensitive: true },
      { key: "institutionalPolicies", label: "Institutional policies", source: "EVIDENCE", required: true },
      { key: "facultyRoster", label: "Faculty roster and credentials", source: "FACULTY", required: true, externallyVerified: true, sensitive: true },
      { key: "academicPrograms", label: "Academic program inventory", source: "ACADEMIC_PROGRAM", required: true },
      { key: "generalEducation", label: "General education matrix", source: "ACADEMIC_PROGRAM", required: true },
      { key: "curriculum", label: "Curriculum exhibits", source: "ACADEMIC_PROGRAM", required: true },
      { key: "learningResources", label: "Learning resources", source: "EVIDENCE", required: true },
      { key: "library", label: "Library resources", source: "EVIDENCE", required: true },
      { key: "studentServices", label: "Student services", source: "EVIDENCE", required: true },
      { key: "admissions", label: "Admissions standards", source: "EVIDENCE", required: true },
      { key: "registrar", label: "Registrar controls", source: "EVIDENCE", required: true },
      { key: "academicRecords", label: "Academic records controls", source: "EVIDENCE", required: true },
      { key: "studentComplaints", label: "Student complaint process", source: "EVIDENCE", required: true },
      { key: "facilitiesTechnology", label: "Facilities and technology", source: "EVIDENCE", required: true },
      { key: "distanceEducation", label: "Distance education controls", source: "EVIDENCE", required: true },
      { key: "institutionalEffectiveness", label: "Institutional effectiveness plan", source: "EVIDENCE", required: true },
      { key: "degreeProgramExhibits", label: "Degree program exhibits", source: "ACADEMIC_PROGRAM", required: true },
      { key: "supportingEvidence", label: "Supporting evidence appendix", source: "EVIDENCE", required: true },
      { key: "siteVisitPreparation", label: "Site visit preparation record", source: "EVIDENCE", required: true },
      { key: "boardAttestation", label: "Board attestation", source: "MANUAL_VERIFIED", required: true, externallyVerified: true },
      { key: "ceoAttestation", label: "CEO attestation", source: "MANUAL_VERIFIED", required: true, externallyVerified: true },
    ],
    requiresHumanApproval: true,
    requiresSignature: true,
    requiresEvidence: true,
    canBeOfficial: true,
  },
  {
    id: "sample-transcript",
    name: "Sample Academic Transcript",
    category: "REGISTRAR",
    classification: "SAMPLE",
    fields: [
      { key: "studentName", label: "Student name", source: "STUDENT_RECORD", required: true, sensitive: true },
      { key: "programName", label: "Program", source: "ACADEMIC_PROGRAM", required: true },
      { key: "courseHistory", label: "Course history", source: "STUDENT_RECORD", required: true, sensitive: true },
      { key: "gpa", label: "GPA", source: "STUDENT_RECORD", required: true, sensitive: true },
    ],
    requiresHumanApproval: true,
    requiresSignature: false,
    requiresEvidence: false,
    canBeOfficial: false,
  },
  {
    id: "sample-diploma",
    name: "Sample Diploma",
    category: "REGISTRAR",
    classification: "SAMPLE",
    fields: [
      { key: "studentName", label: "Student name", source: "STUDENT_RECORD", required: true, sensitive: true },
      { key: "degree", label: "Degree", source: "ACADEMIC_PROGRAM", required: true },
      { key: "major", label: "Major", source: "ACADEMIC_PROGRAM", required: true },
      { key: "conferralDate", label: "Conferral date", source: "STUDENT_RECORD", required: true, externallyVerified: true },
    ],
    requiresHumanApproval: true,
    requiresSignature: true,
    requiresEvidence: true,
    canBeOfficial: false,
  },
  {
    id: "admission-decision-letter",
    name: "Admission Decision Letter",
    category: "COMMUNICATION",
    classification: "INTERNAL",
    fields: [
      { key: "studentName", label: "Applicant name", source: "STUDENT_RECORD", required: true, sensitive: true },
      { key: "applicationId", label: "Application ID", source: "STUDENT_RECORD", required: true, sensitive: true },
      { key: "program", label: "Program", source: "ACADEMIC_PROGRAM", required: true },
      { key: "decision", label: "Decision", source: "MANUAL_VERIFIED", required: true },
    ],
    requiresHumanApproval: true,
    requiresSignature: false,
    requiresEvidence: false,
    canBeOfficial: true,
  },
  {
    id: "student-disciplinary-notice",
    name: "Student Disciplinary Notice",
    category: "DISCIPLINARY",
    classification: "INTERNAL",
    fields: [
      { key: "studentName", label: "Student name", source: "STUDENT_RECORD", required: true, sensitive: true },
      { key: "caseId", label: "Case ID", source: "STUDENT_RECORD", required: true, sensitive: true },
      { key: "policyCitation", label: "Policy citation", source: "EVIDENCE", required: true },
      { key: "findings", label: "Findings", source: "MANUAL_VERIFIED", required: true, sensitive: true },
      { key: "appealRights", label: "Appeal rights", source: "EVIDENCE", required: true },
    ],
    requiresHumanApproval: true,
    requiresSignature: true,
    requiresEvidence: true,
    canBeOfficial: true,
  },
  {
    id: "registrar-enrollment-verification",
    name: "Enrollment Verification",
    category: "REGISTRAR",
    classification: "OFFICIAL",
    fields: [
      { key: "studentName", label: "Student name", source: "STUDENT_RECORD", required: true, sensitive: true },
      { key: "studentId", label: "Student ID", source: "STUDENT_RECORD", required: true, sensitive: true },
      { key: "term", label: "Term", source: "STUDENT_RECORD", required: true },
      { key: "enrollmentStatus", label: "Enrollment status", source: "STUDENT_RECORD", required: true, externallyVerified: true },
      { key: "programAuthorization", label: "Program authorization", source: "EVIDENCE", required: true, externallyVerified: true },
    ],
    requiresHumanApproval: true,
    requiresSignature: true,
    requiresEvidence: true,
    canBeOfficial: true,
  },
];

export const getUniversityDocumentTemplate = (id: string) =>
  universityDocumentTemplates.find((template) => template.id === id);
