export const regulatoryApplicationSeed = {
  institution: {
    applicantLegalName: "Ross Tax Pro Software Co.",
    proposedInstitutionName: "Ross Tax Pro University",
    entityType: "for_profit_corporation",
    formationJurisdiction: "Arkansas",
    formationDate: "2026-04-06",
    entityId: "811606215",
    proposedTexasLocation: {
      street: "2509 Cody Poe Rd Unit B",
      city: "Killeen",
      state: "TX",
      postalCode: "76549",
    },
    website: "https://rosstaxsoftware.com",
    deliveryModel: ["ONLINE", "SYNCHRONOUS_VIRTUAL", "ASYNCHRONOUS"],
    actualDegreeStudentHeadcount: 0,
  },
  regulatoryStatus: {
    texasDegreeAuthority: "NOT_VERIFIED",
    institutionalAccreditation: "NOT_VERIFIED",
    titleIv: "DISABLED",
    opeid: "NOT_ASSIGNED_OR_VERIFIED",
    federalSchoolCode: "NOT_ASSIGNED_OR_VERIFIED",
    eduDomain: "NOT_VERIFIED",
    degreeEnrollment: "DISABLED",
    degreeConferral: "DISABLED",
    syntheticEnrollment: "ENABLED",
  },
  proposedPrograms: [
    { code: "AS-ACCT", name: "Accounting", credential: "AS", status: "PROPOSED" },
    { code: "BS-ACCT", name: "Accounting", credential: "BS", status: "PROPOSED" },
    { code: "AA-BUS", name: "Business Administration", credential: "AA", status: "PROPOSED" },
    { code: "BA-BUS", name: "Business Administration", credential: "BA", status: "PROPOSED" },
  ],
  sections: [
    { id: 1, key: "institution_identity", title: "Institution Identity", status: "SEEDED", evidenceRequired: true },
    { id: 2, key: "legal_organization", title: "Legal Organization", status: "SEEDED", evidenceRequired: true },
    { id: 3, key: "governing_board", title: "Governing Board", status: "PARTIALLY_SEEDED", evidenceRequired: true },
    { id: 4, key: "chief_executive_administration", title: "Chief Executive Administration", status: "PARTIALLY_SEEDED", evidenceRequired: true },
    { id: 5, key: "institutional_mission", title: "Institutional Mission", status: "SEEDED", evidenceRequired: false },
    { id: 6, key: "financial_capacity", title: "Financial Capacity", status: "DOCUMENTS_REQUIRED", evidenceRequired: true },
    { id: 7, key: "surety_instrument", title: "Surety Instrument", status: "DOCUMENTS_REQUIRED", evidenceRequired: true },
    { id: 8, key: "institutional_policies", title: "Institutional Policies", status: "DRAFT_LIBRARY_READY", evidenceRequired: true },
    { id: 9, key: "faculty", title: "Faculty", status: "CREDENTIAL_VERIFICATION_REQUIRED", evidenceRequired: true },
    { id: 10, key: "academic_programs", title: "Academic Programs", status: "PROPOSED", evidenceRequired: true },
    { id: 11, key: "general_education", title: "General Education", status: "CURRICULUM_VALIDATION_REQUIRED", evidenceRequired: true },
    { id: 12, key: "curriculum", title: "Curriculum", status: "CURRICULUM_VALIDATION_REQUIRED", evidenceRequired: true },
    { id: 13, key: "learning_resources", title: "Learning Resources", status: "RESOURCE_LICENSE_VERIFICATION_REQUIRED", evidenceRequired: true },
    { id: 14, key: "library", title: "Library", status: "RESOURCE_LICENSE_VERIFICATION_REQUIRED", evidenceRequired: true },
    { id: 15, key: "student_services", title: "Student Services", status: "ARCHITECTURE_READY", evidenceRequired: true },
    { id: 16, key: "admissions", title: "Admissions", status: "ARCHITECTURE_READY_DEGREE_ENROLLMENT_LOCKED", evidenceRequired: true },
    { id: 17, key: "registrar", title: "Registrar", status: "ARCHITECTURE_READY_CONFERRAL_LOCKED", evidenceRequired: true },
    { id: 18, key: "academic_records", title: "Academic Records", status: "ARCHITECTURE_READY", evidenceRequired: true },
    { id: 19, key: "student_complaints", title: "Student Complaints", status: "POLICY_REVIEW_REQUIRED", evidenceRequired: true },
    { id: 20, key: "facilities_technology", title: "Facilities / Technology", status: "PARTIALLY_SEEDED", evidenceRequired: true },
    { id: 21, key: "distance_education", title: "Distance Education", status: "ARCHITECTURE_READY", evidenceRequired: true },
    { id: 22, key: "institutional_effectiveness", title: "Institutional Effectiveness", status: "ASSESSMENT_PLAN_REQUIRED", evidenceRequired: true },
    { id: 23, key: "degree_program_exhibits", title: "Degree Program Exhibits", status: "GENERATION_READY", evidenceRequired: true },
    { id: 24, key: "supporting_evidence", title: "Supporting Evidence", status: "EVIDENCE_COLLECTION_REQUIRED", evidenceRequired: true },
    { id: 25, key: "site_visit_preparation", title: "Site Visit Preparation", status: "SIMULATION_READY", evidenceRequired: true },
    { id: 26, key: "certification_attestation", title: "Certification / Attestation", status: "HUMAN_SIGNATURE_REQUIRED", evidenceRequired: true },
  ],
  mission:
    "Ross Tax Pro University is proposed as a career-connected postsecondary institution designed to provide accessible, technology-enabled collegiate education in business, accounting, taxation, administration, and related disciplines through structured curricula, synchronous virtual instruction, asynchronous learning, assessment, academic advising, experiential application, and technology-supported student services.",
  hardGates: {
    officialDegreeAdvertising: false,
    actualDegreeEnrollment: false,
    degreeCreditAward: false,
    degreeConferral: false,
    titleIvProcessing: false,
    federalEnrollmentTransmission: false,
    officialEduDomainClaim: false,
  },
} as const;
