import Link from "next/link";
import { universities, universityPersonas } from "@/lib/university";

export default function UniversitiesPage() {
  return <main><header><Link href="/"><b>ROSS TAX PRO SOFTWARE CO.</b></Link><nav><Link href="/platforms">Platforms</Link><Link href="/training">Training</Link><Link href="/students">Students</Link><Link href="/sign-in">Sign In</Link></nav></header>
    <section className="pageHero"><p className="eyebrow">100% ONLINE EDUCATION</p><h1>AI-powered learning.<br/><em>Human-accountable governance.</em></h1><p className="lede">Ross Tax Pro University and Ross E-Drive University deliver online learning through governed AI faculty, tutoring, student-success, registrar, and curriculum personas—with human approval retained for consequential academic decisions.</p><div className="actions"><Link className="button primary" href="/learn">Enter learning workspace</Link><Link className="button" href="/students">Explore student resources</Link></div></section>
    <section><div className="heading"><div><p className="eyebrow">INSTITUTIONS</p><h2>Online from enrollment through completion.</h2></div><p>Program availability, regulatory recognition, tuition, and credential eligibility must be verified for each offering before enrollment or advertising.</p></div><div className="cards light">{Object.values(universities).map(u=><article key={u.code}><span>{u.code.toUpperCase()}</span><h3>{u.name}</h3><p>{u.statement}</p><Link className="button" href={`/universities/${u.slug}`}>View programs</Link></article>)}</div><div className="actions"><Link className="button" href="/universities/governance">Governance registry</Link><Link className="button primary" href="/office/regulatory">Regulatory application</Link></div></section>
    <section className="dark"><div className="heading"><div><p className="eyebrow">AI FACULTY & STAFF</p><h2>Always available. Never unaccountable.</h2></div><p>AI personas support instruction and operations within documented authority, audit, privacy, accessibility, and human-review boundaries.</p></div><div className="cards">{universityPersonas.map(p=><article key={p.code}><span>{p.title}</span><h3>{p.function}</h3><p>{p.approval}</p></article>)}</div><div className="actions"><Link className="button primary" href="/universities/academics">Explore academic pathways</Link></div></section><footer><p>© 2026 Ross Tax Pro Software Co. Online education is subject to published enrollment terms and human academic oversight.</p><Link href="/support">Student support</Link></footer></main>;
}
