"use client";
import {useState} from "react";
import {departments,platformCoverage,positions,priorityPolicy,seededTickets,type SupportPriority,type SupportQueue} from "@/lib/support-operations";
type Guidance={classification:string;steps:string[];requiresApproval:boolean;disclaimer:string};
export default function SupportConsole(){const [queue,setQueue]=useState<SupportQueue>("customer_care"),[priority,setPriority]=useState<SupportPriority>("P3"),[summary,setSummary]=useState(""),[guidance,setGuidance]=useState<Guidance|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);async function generate(){setLoading(true);setError("");setGuidance(null);try{const r=await fetch("/api/support/guidance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({queue,priority,summary})}),v=await r.json();if(!r.ok)throw new Error(v.error||"Guidance unavailable");setGuidance(v)}catch(e){setError(e instanceof Error?e.message:"Guidance unavailable")}finally{setLoading(false)}}return <>
<section className="supportStats" aria-label="Support service levels">{Object.entries(priorityPolicy).map(([code,p])=><article key={code}><span>{code} · {p.label}</span><strong>{p.acknowledgeMinutes}m</strong><small>Acknowledge target</small></article>)}</section>
<section><div className="heading"><div><p className="eyebrow">LIVE OPERATIONS</p><h2>Queue command</h2></div><p>Seeded scenarios contain no real taxpayer data. Production records belong only in authorized encrypted systems.</p></div><div className="supportGrid"><div className="ticketList">{seededTickets.map(t=><article key={t.id}><div><b>{t.id}</b><span className={`priority ${t.priority.toLowerCase()}`}>{t.priority}</span></div><h3>{t.subject}</h3><p>{t.next}</p><small>{t.platform} · {t.status}</small></article>)}</div><div className="reasoningPanel"><p className="eyebrow">REP ASSIST</p><h3>Controlled next-action guidance</h3><label>Queue<select value={queue} onChange={e=>setQueue(e.target.value as SupportQueue)}>{[...new Set(platformCoverage.map(x=>x.queue)),"customer_care","identity_access","billing","integrations","security","outage"].map(q=><option key={q} value={q}>{q.replaceAll("_"," ")}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value as SupportPriority)}>{Object.keys(priorityPolicy).map(p=><option key={p}>{p}</option>)}</select></label><label>Sanitized issue summary<textarea value={summary} onChange={e=>setSummary(e.target.value)} rows={5} placeholder="Facts and impact only. Never enter SSNs, passwords, MFA codes, bank details or taxpayer documents."/></label><button className="button primary" onClick={generate} disabled={loading||summary.trim().length<8}>{loading?"Evaluating…":"Generate next actions"}</button>{error?<p role="alert" className="formError">{error}</p>:null}{guidance?<div className="guidance" aria-live="polite"><b>{guidance.classification.replaceAll("_"," ")} · {guidance.requiresApproval?"Approval required":"Representative-authorized"}</b><ol>{guidance.steps.map(s=><li key={s}>{s}</li>)}</ol><small>{guidance.disclaimer}</small></div>:null}</div></div></section>
<section className="dark"><div className="heading"><div><p className="eyebrow">ENTERPRISE COVERAGE</p><h2>One department. Every platform.</h2></div><p>Specialists share a single intake model while retaining platform ownership, access boundaries and escalation accountability.</p></div><div className="positionGrid">{departments.map(d=><article key={d.code}><span>{d.name}</span><p>{d.coverage}</p><ul>{d.roles.map(r=><li key={r}>{r}</li>)}</ul></article>)}</div></section>
<section><div className="heading"><div><p className="eyebrow">ROLE PERSONAS</p><h2>Authority without ambiguity</h2></div></div><div className="positionGrid lightPositions">{positions.map(p=><article key={p.title}><span>{p.title}</span><h3>{p.persona}</h3><p><b>Owns:</b> {p.owns}</p><p><b>Never:</b> {p.never}</p></article>)}</div></section></>}
