import {ClerkProvider,useAuth,useUser} from "@clerk/expo";
import {useHostedAuth} from "@clerk/expo/hosted-auth";
import {tokenCache} from "@clerk/expo/token-cache";
import {SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,TouchableOpacity,View} from "react-native";

const navy="#071A32",gold="#C8A44D",cream="#F8F4EC",ink="#152238";
const platforms=["Virtual Office","eTRAC Refund Intelligence","Tax Pro University","E-Drive University","Prime Payroll & HR","PDF Editor"];

function SignIn(){const {startHostedAuth}=useHostedAuth();return <SafeAreaView style={styles.auth}><View style={styles.mark}><Text style={styles.markText}>R</Text></View><Text style={styles.kicker}>ROSS TAX PRO SOFTWARE CO.</Text><Text style={styles.hero}>Secure work.{"\n"}<Text style={styles.gold}>Anywhere.</Text></Text><Text style={styles.copy}>One protected mobile gateway for customer care, IT support, tax-practice operations, education and workforce services.</Text><TouchableOpacity accessibilityRole="button" style={styles.primary} onPress={()=>startHostedAuth()}><Text style={styles.primaryText}>Sign in securely</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" style={styles.secondary} onPress={()=>startHostedAuth({mode:"sign-up"})}><Text style={styles.secondaryText}>Create authorized account</Text></TouchableOpacity><Text style={styles.privacy}>Never share passwords, MFA codes, full SSNs, bank details or tax documents in ordinary chat.</Text></SafeAreaView>}

function Workspace(){const {signOut}=useAuth(),{user}=useUser();return <SafeAreaView style={styles.shell}><StatusBar barStyle="light-content"/><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><View><Text style={styles.kickerLight}>ROSS TAX PRO · NATIVE OFFICE</Text><Text style={styles.welcome}>Welcome, {user?.firstName||"authorized user"}</Text></View><TouchableOpacity accessibilityRole="button" onPress={()=>signOut()}><Text style={styles.signOut}>Sign out</Text></TouchableOpacity></View><View style={styles.heroCard}><Text style={styles.kickerLight}>ENTERPRISE COMMAND</Text><Text style={styles.heroSmall}>Every division.{"\n"}<Text style={styles.gold}>One secure access point.</Text></Text><Text style={styles.copyLight}>Clerk identity, minimum-necessary access and auditable support workflows travel with the operator.</Text></View><Text style={styles.sectionTitle}>Platforms</Text><View style={styles.grid}>{platforms.map((p,i)=><TouchableOpacity accessibilityRole="button" key={p} style={styles.card}><Text style={styles.cardIndex}>0{i+1}</Text><Text style={styles.cardTitle}>{p}</Text><Text style={styles.cardLink}>Open workspace →</Text></TouchableOpacity>)}</View><View style={styles.alert}><Text style={styles.alertTitle}>Live Support Command</Text><Text style={styles.alertBody}>Authenticate, classify, verify facts, resolve or escalate, communicate, and preserve the interaction record.</Text></View></ScrollView></SafeAreaView>}

function Root(){const {isLoaded,isSignedIn}=useAuth();if(!isLoaded)return <SafeAreaView style={styles.auth}><Text style={styles.kicker}>SECURELY INITIALIZING…</Text></SafeAreaView>;return isSignedIn?<Workspace/>:<SignIn/>}

export default function App(){const key=process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY;if(!key)return <SafeAreaView style={styles.auth}><Text style={styles.hero}>Configuration required.</Text><Text style={styles.copy}>Set EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY through the approved build environment. Never embed a Clerk secret key in a native application.</Text></SafeAreaView>;return <ClerkProvider publishableKey={key} tokenCache={tokenCache}><Root/></ClerkProvider>}

const styles=StyleSheet.create({shell:{flex:1,backgroundColor:cream},content:{paddingBottom:40},auth:{flex:1,justifyContent:"center",padding:28,backgroundColor:cream},mark:{width:72,height:72,borderRadius:18,backgroundColor:navy,borderWidth:2,borderColor:gold,alignItems:"center",justifyContent:"center",marginBottom:24},markText:{color:gold,fontSize:44,fontWeight:"800"},kicker:{color:"#86651F",fontSize:12,fontWeight:"800",letterSpacing:1.6},kickerLight:{color:gold,fontSize:11,fontWeight:"800",letterSpacing:1.3},hero:{color:navy,fontSize:46,lineHeight:50,fontWeight:"800",marginVertical:18},heroSmall:{color:"white",fontSize:35,lineHeight:39,fontWeight:"800",marginVertical:14},gold:{color:gold},copy:{color:"#526075",fontSize:16,lineHeight:25,marginBottom:26},copyLight:{color:"#C4CEDA",fontSize:15,lineHeight:23},primary:{backgroundColor:navy,padding:17,alignItems:"center",marginBottom:12},primaryText:{color:"white",fontWeight:"800"},secondary:{borderWidth:1,borderColor:navy,padding:16,alignItems:"center"},secondaryText:{color:navy,fontWeight:"800"},privacy:{color:"#687383",fontSize:12,lineHeight:18,marginTop:24},top:{backgroundColor:navy,paddingHorizontal:22,paddingTop:24,paddingBottom:20,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},welcome:{color:"white",fontSize:21,fontWeight:"700",marginTop:7},signOut:{color:gold,fontWeight:"800"},heroCard:{backgroundColor:"#102A4A",margin:16,padding:26,borderTopWidth:3,borderTopColor:gold},sectionTitle:{color:navy,fontSize:28,fontWeight:"800",paddingHorizontal:18,marginVertical:12},grid:{paddingHorizontal:16,flexDirection:"row",flexWrap:"wrap",gap:10},card:{width:"48%",minHeight:145,backgroundColor:"white",borderWidth:1,borderColor:"#DED7CA",padding:16},cardIndex:{color:gold,fontWeight:"800",fontSize:12},cardTitle:{color:ink,fontSize:17,fontWeight:"800",marginTop:14},cardLink:{color:"#687383",fontSize:12,marginTop:"auto"},alert:{margin:16,padding:22,backgroundColor:"#EFE5D3",borderLeftWidth:4,borderLeftColor:gold},alertTitle:{color:navy,fontWeight:"800",fontSize:18},alertBody:{color:"#526075",lineHeight:21,marginTop:8}});
