export type LetterGrade="A"|"B"|"C"|"D"|"F"|"P"|"NP"|"I"|"W";
export type GradeRecord={courseCode:string;credits:number;grade:LetterGrade};
export type Assignment={id:string;title:string;pointsEarned:number|null;pointsPossible:number;dueAt:string;submittedAt?:string};
export type AttendanceEvent={meetingId:string;status:"present"|"late"|"excused"|"absent";minutesPresent:number;minutesScheduled:number};
const gradePoints:Partial<Record<LetterGrade,number>>={A:4,B:3,C:2,D:1,F:0};
export function calculateGpa(records:readonly GradeRecord[]){const graded=records.filter(r=>gradePoints[r.grade]!==undefined&&Number.isFinite(r.credits)&&r.credits>0);const attemptedCredits=graded.reduce((s,r)=>s+r.credits,0);const qualityPoints=graded.reduce((s,r)=>s+r.credits*(gradePoints[r.grade]??0),0);return{attemptedCredits,qualityPoints:Number(qualityPoints.toFixed(3)),gpa:attemptedCredits?Number((qualityPoints/attemptedCredits).toFixed(3)):null}}
export function calculateAssignmentAverage(items:readonly Assignment[]){const graded=items.filter(a=>a.pointsEarned!==null&&a.pointsPossible>0);const earned=graded.reduce((s,a)=>s+(a.pointsEarned??0),0),possible=graded.reduce((s,a)=>s+a.pointsPossible,0);return possible?Number((earned/possible*100).toFixed(2)):null}
export function calculateAttendance(items:readonly AttendanceEvent[]){const scheduled=items.reduce((s,e)=>s+Math.max(0,e.minutesScheduled),0),attended=items.reduce((s,e)=>s+Math.min(Math.max(0,e.minutesPresent),Math.max(0,e.minutesScheduled)),0);return{attendedMinutes:attended,scheduledMinutes:scheduled,attendanceRate:scheduled?Number((attended/scheduled*100).toFixed(2)):null}}
export function accountabilityFlags(i:{assignmentAverage:number|null;attendanceRate:number|null;gpa:number|null}){const f:string[]=[];if(i.assignmentAverage!==null&&i.assignmentAverage<70)f.push("ACADEMIC_SUPPORT_REVIEW");if(i.attendanceRate!==null&&i.attendanceRate<80)f.push("ATTENDANCE_OUTREACH");if(i.gpa!==null&&i.gpa<2)f.push("ACADEMIC_STANDING_REVIEW");return f}
export const accountabilityRules={gradeSource:"Instructor-approved entries only",recalculation:"Deterministic and audit logged",enforcement:"Flags create human review tasks; no automatic discipline",appeals:"Notice, evidence access, response, and appeal",aiBoundary:"AI cannot assign final grades or sanctions"} as const;
export const syntheticProgress={learner:"Synthetic Student 001",program:"Certificate Level I — Tax Practice Foundations",term:"Fall 2026",grades:[{courseCode:"TAX-101",credits:3,grade:"A"},{courseCode:"ACC-110",credits:3,grade:"B"}] satisfies GradeRecord[],assignments:[{id:"a1",title:"Filing Status Analysis",pointsEarned:92,pointsPossible:100,dueAt:"2026-09-14T23:59:00Z",submittedAt:"2026-09-13T18:20:00Z"},{id:"a2",title:"Ledger Reconciliation",pointsEarned:84,pointsPossible:100,dueAt:"2026-09-21T23:59:00Z"}] satisfies Assignment[],attendance:[{meetingId:"m1",status:"present",minutesPresent:75,minutesScheduled:75},{meetingId:"m2",status:"late",minutesPresent:60,minutesScheduled:75}] satisfies AttendanceEvent[],schedule:[{course:"TAX-101",event:"Live lecture",startsAt:"2026-09-10T23:00:00Z",mode:"online"},{course:"ACC-110",event:"Faculty office hour",startsAt:"2026-09-12T18:00:00Z",mode:"online"}],degreeAudit:{requiredCredits:18,earnedCredits:6,inProgressCredits:6,minimumGpa:2,requirements:["TAX-101","ACC-110","ETH-120","TAX-130","CAP-190"]}} as const;
