export type AcademicProgram={slug:string;award:string;title:string;credits:number;status:"proposed"|"non-degree"|"preparatory";school:string;description:string;courses:string[]};
const businessCore=["ACCT 2301 Financial Accounting","ACCT 2302 Managerial Accounting","BUSI 1301 Business Principles","ECON 2301 Macroeconomics","ECON 2302 Microeconomics","MATH 1324 Business Mathematics","BUSI 2305 Business Statistics","BCIS 1305 Business Applications"];
const generalCore=["ENGL 1301 Composition I","ENGL 1302 Composition II","SPCH 1311 Professional Communication","HIST 1301 United States History I","HIST 1302 United States History II","GOVT 2305 Federal Government","GOVT 2306 Texas Government","Life and Physical Science I","Life and Physical Science II","Creative Arts","Language, Philosophy and Culture"];
export const academicPrograms:AcademicProgram[]=[
 {slug:"tax-preparation-certificate-i",award:"Certificate Level I",title:"Tax Preparation Foundations",credits:18,status:"non-degree",school:"School of Tax Practice",description:"Entry pathway in individual taxation, due diligence, ethics, intake, research and supervised preparation.",courses:["TAX 1101 Profession and Ethics","TAX 1301 Individual Taxation I","TAX 1302 Filing Status and Dependents","TAX 1303 Income and Adjustments","TAX 1304 Credits and Due Diligence","TAX 1205 Practice Laboratory I"]},
 {slug:"tax-practitioner-certificate-ii",award:"Certificate Level II",title:"Advanced Tax Practice and Representation",credits:30,status:"non-degree",school:"School of Tax Practice",description:"Advanced pathway in business returns, procedure, notices, transcript analysis and governed casework.",courses:["TAX 2301 Individual Taxation II","TAX 2302 Schedule C and Entity Fundamentals","TAX 2303 Tax Research and Writing","TAX 2304 IRS Procedure and Notices","TAX 2305 Transcript Analysis","TAX 2206 Practice Laboratory II","TAX 2307 Cybersecurity and Taxpayer Privacy","TAX 2208 Supervised Capstone"]},
 {slug:"tax-practitioner-diploma",award:"Diploma",title:"Professional Tax Practitioner",credits:45,status:"non-degree",school:"School of Tax Practice",description:"Stackable professional diploma combining both certificate levels with client service, office operations and practicum.",courses:[...businessCore.slice(0,2),"TAX 1101 Profession and Ethics","TAX 1301 Individual Taxation I","TAX 1304 Credits and Due Diligence","TAX 2301 Individual Taxation II","TAX 2302 Schedule C and Entity Fundamentals","TAX 2303 Tax Research and Writing","TAX 2304 IRS Procedure and Notices","TAX 2305 Transcript Analysis","TAX 2307 Cybersecurity and Taxpayer Privacy","MGMT 2301 Tax Office Operations","TAX 2388 Practicum","TAX 2399 Capstone"]},
 {slug:"aa-business-administration",award:"Proposed Associate of Arts",title:"Business Administration",credits:60,status:"proposed",school:"School of Business and Accounting",description:"Transfer-oriented foundation mapped to the Texas business field of study and general education framework.",courses:[...generalCore,...businessCore,"Electives (9 SCH)"]},
 {slug:"aa-accounting",award:"Proposed Associate of Arts",title:"Accounting",credits:60,status:"proposed",school:"School of Business and Accounting",description:"Lower-division accounting pathway with business, technology, economics and general education foundations.",courses:[...generalCore,...businessCore,"ACCT 2303 Accounting Information Systems","ACCT 2304 Payroll Accounting","Electives (3 SCH)"]},
 {slug:"bba-accounting",award:"Proposed Bachelor of Business Administration",title:"Accounting",credits:120,status:"proposed",school:"School of Business and Accounting",description:"Four-year accounting curriculum inspired by established HBCU business-school rigor without copying or claiming affiliation.",courses:[...generalCore,...businessCore,"ACCT 3301 Intermediate Accounting I","ACCT 3302 Intermediate Accounting II","ACCT 3303 Cost Accounting","ACCT 3304 Federal Income Taxation","ACCT 4301 Auditing","ACCT 4302 Accounting Information Systems","ACCT 4303 Governmental and Nonprofit Accounting","ACCT 4304 Advanced Accounting","FINA 3301 Financial Management","MGMT 3301 Organizational Leadership","MKTG 3301 Marketing","BLAW 3301 Legal Environment","MGSC 3301 Operations","CAP 4399 Accounting Strategy Capstone","Advanced electives (15 SCH)"]},
 {slug:"bba-business-administration",award:"Proposed Bachelor of Business Administration",title:"Business Administration",credits:120,status:"proposed",school:"School of Business and Accounting",description:"Leadership, finance, accounting, marketing, operations, analytics, law and entrepreneurship with an HBCU-centered community impact lens.",courses:[...generalCore,...businessCore,"FINA 3301 Financial Management","MGMT 3301 Organizational Leadership","MKTG 3301 Marketing","BLAW 3301 Legal Environment","MGSC 3301 Operations","MIS 3301 Business Systems","ENTR 3301 Entrepreneurship","BUSI 4301 Strategy","BUSI 4302 Global Business","BUSI 4303 Business Analytics","CAP 4399 Community Enterprise Capstone","Concentration electives (21 SCH)"]},
 {slug:"bba-management-hr",award:"Proposed BBA Concentration",title:"Management and Human Resources",credits:120,status:"proposed",school:"School of Business and Accounting",description:"Management degree pathway emphasizing people operations, employment systems, workforce analytics and ethical leadership.",courses:[...generalCore,...businessCore,"MGMT 3301 Organizational Leadership","HRM 3301 Human Resource Management","HRM 3302 Employment Law","HRM 3303 Compensation and Benefits","HRM 4301 Talent Development","HRM 4302 Workforce Analytics","MGMT 4303 Negotiation","CAP 4399 Workforce Strategy Capstone","Business electives (24 SCH)"]},
 {slug:"bba-management-information-systems",award:"Proposed Bachelor of Business Administration",title:"Management Information Systems",credits:120,status:"proposed",school:"School of Business and Accounting",description:"Business systems, data, cybersecurity, automation and responsible AI for organizational decision-making.",courses:[...generalCore,...businessCore,"MIS 3301 Systems Analysis","MIS 3302 Database Management","MIS 3303 Enterprise Applications","MIS 3304 Cybersecurity Governance","MIS 4301 Cloud Systems","MIS 4302 Business Analytics","MIS 4303 Responsible AI","CAP 4399 Digital Enterprise Capstone","Business and technical electives (24 SCH)"]},
 {slug:"adult-education-ged-fast-track",award:"Preparation Program",title:"Texas GED Fast-Track",credits:0,status:"preparatory",school:"School of Adult and Continuing Education",description:"Diagnostic preparation for the four current GED subject tests; the official TxCHSE is issued through the state testing process, not by Ross Tax Pro University.",courses:["GED-RLA Reasoning Through Language Arts","GED-MATH Mathematical Reasoning","GED-SCI Science","GED-SS Social Studies","GED-READY Official Readiness Planning","COLL 0100 College and Career Transition"]},
 {slug:"texas-home-education-diploma",award:"Private Homeschool Curriculum Pathway",title:"Texas High School Diploma Pathway",credits:22,status:"preparatory",school:"School of Secondary and Adult Education",description:"Parent-directed bona fide written curriculum meeting Texas homeschool subject minimums and using the 22-credit Foundation plan as a voluntary rigor benchmark.",courses:["English I","English II","English III","Advanced English","Algebra I","Geometry","Advanced Mathematics","Biology","Integrated Physics and Chemistry","Advanced Science","World Geography or World History","United States History","United States Government (0.5)","Economics and Personal Financial Literacy (0.5)","Physical Education","Languages Other Than English I","Languages Other Than English II","Fine Arts","Digital Citizenship and Safety","Electives (5 SCH)"]},
];
export const academicProgramBySlug=(slug:string)=>academicPrograms.find(program=>program.slug===slug);
