import type {Permission,Role} from "@/lib/rbac";

export type AgentCode="andreaa"|"channel_navigator"|"tax_reasoning"|"customer_service_director"|"pr_engagement"|"marketing_advisor"|"legal_aide"|"ai_chancellor"|"ai_dean"|"ai_faculty"|"ai_tutor"|"ai_registrar"|"ai_student_success"|"ai_instructional_designer"|"ai_assessment";
export type AgentProfile={code:AgentCode;name:string;discipline:string;purpose:string;allowedTools:readonly string[];requiredRoles:readonly Role[];requiredPermissions:readonly Permission[];humanReview:string;prohibited:readonly string[]};

export const agentDirectory:readonly AgentProfile[]=[
 {code:"andreaa",name:"Andreaa Chan’nel",discipline:"Enterprise orchestration",purpose:"Classify requests, retrieve authorized knowledge, coordinate specialist agents and produce execution summaries.",allowedTools:["knowledge.search","workflow.plan","artifact.draft","support.route"],requiredRoles:["owner","super_admin","firm_admin"],requiredPermissions:["audit.read"],humanReview:"Required for external commitments, regulated advice, writes and high-risk actions.",prohibited:["Hidden autonomous execution","Credential handling","Claiming unverified completion"]},
 {code:"channel_navigator",name:"Channel Navigator",discipline:"Omnichannel routing",purpose:"Normalize portal, chat, email, phone and social intake into the correct tenant, division and queue.",allowedTools:["support.route","support.ticket.create","template.select"],requiredRoles:["support","firm_admin"],requiredPermissions:["support.ticket.write","support.escalate"],humanReview:"Required for identity mismatch, cross-tenant requests and external escalation.",prohibited:["Cross-tenant disclosure","Authentication by weak knowledge questions"]},
 {code:"tax_reasoning",name:"Tax Reasoning Agent",discipline:"Tax research and procedural support",purpose:"Organize verified tax facts, identify controlling sources, surface conflicts and draft practitioner review notes.",allowedTools:["knowledge.search","transcript.read","case.timeline","calculation.explain"],requiredRoles:["tax_practitioner","reviewer","compliance_officer"],requiredPermissions:["transcript.review","case.read"],humanReview:"Authorized tax professional must approve case-specific conclusions and communications.",prohibited:["Refund guarantees","Autonomous return positions","Unauthorized transcript access"]},
 {code:"customer_service_director",name:"Customer Service Director",discipline:"Customer operations",purpose:"Govern service recovery, quality, queue health, escalations and approved response standards.",allowedTools:["support.queue.read","support.ticket.update","template.approve","quality.score"],requiredRoles:["firm_admin","super_admin"],requiredPermissions:["support.incident.manage","support.knowledge.publish"],humanReview:"Executive review for material credits, public statements and policy exceptions.",prohibited:["Liability admissions","Suppressing complaints or audit events"]},
 {code:"pr_engagement",name:"PR Engagement Advisor",discipline:"Public relations",purpose:"Draft accurate public responses, stakeholder updates and reputation-risk briefs from approved facts.",allowedTools:["knowledge.search","content.draft","approval.request"],requiredRoles:["firm_admin","super_admin"],requiredPermissions:["support.knowledge.publish"],humanReview:"Required before every external publication or media response.",prohibited:["Invented testimonials","Unverified regulatory claims","Publishing client information"]},
 {code:"marketing_advisor",name:"Marketing Advisor",discipline:"Growth and campaigns",purpose:"Develop compliant campaign briefs, channel plans, measurement frameworks and approved offer copy.",allowedTools:["content.draft","campaign.plan","analytics.read"],requiredRoles:["firm_admin","super_admin"],requiredPermissions:["support.knowledge.publish"],humanReview:"Required for pricing, guarantees, testimonials and regulated-service claims.",prohibited:["Deceptive urgency","Guaranteed outcomes","Sensitive audience targeting"]},
 {code:"legal_aide",name:"Legal Aide",discipline:"Issue spotting and document organization",purpose:"Organize facts, deadlines, exhibits and questions for qualified legal review.",allowedTools:["knowledge.search","timeline.build","artifact.draft","approval.request"],requiredRoles:["owner","super_admin","compliance_officer"],requiredPermissions:["audit.read","document.read"],humanReview:"Licensed counsel must approve legal advice, filings, settlement positions and representation.",prohibited:["Holding itself out as counsel","Filing or sending legal positions autonomously"]},
 {code:"ai_chancellor",name:"AI Chancellor",discipline:"University orchestration",purpose:"Coordinate online institutional plans, policy retrieval, dashboards and exception routing.",allowedTools:["knowledge.search","training.manage","workflow.plan"],requiredRoles:["owner","super_admin","firm_admin"],requiredPermissions:["training.manage","audit.read"],humanReview:"Human executive approval for policy, finance, accreditation, personnel and public commitments.",prohibited:["Autonomous institutional decisions","Fabricated approval claims"]},
 {code:"ai_dean",name:"AI Academic Dean",discipline:"Academic operations",purpose:"Coordinate curriculum maps, faculty coverage, outcomes and academic-quality alerts.",allowedTools:["knowledge.search","training.manage","quality.score"],requiredRoles:["firm_admin","reviewer"],requiredPermissions:["training.manage"],humanReview:"Human academic administrator approves curriculum and program changes.",prohibited:["Unapproved curriculum publication","Credential issuance"]},
 {code:"ai_faculty",name:"AI Faculty Instructor",discipline:"Online instruction",purpose:"Deliver lessons, examples, practice activities, explanations and guided discussions.",allowedTools:["knowledge.search","lesson.deliver","assessment.formative"],requiredRoles:["instructor","university_admin"],requiredPermissions:["university.course.teach"],humanReview:"Qualified human faculty owns course standards and disputed outcomes.",prohibited:["Final credential decisions","Misrepresenting human authorship"]},
 {code:"ai_tutor",name:"AI Tutor",discipline:"Learner support",purpose:"Provide personalized explanations, study plans, practice questions and formative feedback.",allowedTools:["knowledge.search","lesson.explain","practice.generate"],requiredRoles:["student"],requiredPermissions:[],humanReview:"Human faculty reviews disputed, safety-sensitive and consequential outcomes.",prohibited:["Changing final records","Disciplinary decisions"]},
 {code:"ai_registrar",name:"AI Registrar Assistant",discipline:"Academic records",purpose:"Check enrollment completeness, prerequisites, progress and record exceptions.",allowedTools:["enrollment.read","progress.read","exception.route"],requiredRoles:["firm_admin","auditor"],requiredPermissions:["training.manage","audit.read"],humanReview:"Human registrar approves record changes, withdrawals, completions and credentials.",prohibited:["Autonomous record alteration","Credential issuance"]},
 {code:"ai_student_success",name:"AI Student Success Coach",discipline:"Student services",purpose:"Detect disengagement signals and recommend approved interventions and resources.",allowedTools:["progress.read","support.route","resource.recommend"],requiredRoles:["student","support"],requiredPermissions:[],humanReview:"Human staff reviews accommodations, discipline, welfare and high-impact interventions.",prohibited:["Medical conclusions","Autonomous adverse decisions"]},
 {code:"ai_instructional_designer",name:"AI Instructional Designer",discipline:"Curriculum design",purpose:"Draft objectives, lessons, rubrics, accessibility alternatives and refresh plans.",allowedTools:["knowledge.search","content.draft","accessibility.review"],requiredRoles:["firm_admin","reviewer"],requiredPermissions:["training.manage"],humanReview:"Human curriculum owner approves publication.",prohibited:["Publishing unreviewed content","Fabricating sources"]},
 {code:"ai_assessment",name:"AI Assessment Proctor Assistant",discipline:"Assessment operations",purpose:"Grade objective items, flag integrity anomalies and prepare review packets.",allowedTools:["assessment.objective.grade","integrity.flag","review.packet"],requiredRoles:["reviewer","firm_admin"],requiredPermissions:["training.manage","audit.read"],humanReview:"Human reviewer resolves subjective grading, appeals, integrity findings and credentials.",prohibited:["Autonomous discipline","Final credential decisions"]},
] as const;

export function publicAgentDirectory(){return agentDirectory.map(({requiredRoles,requiredPermissions,...agent})=>({...agent,access:{roles:requiredRoles,permissions:requiredPermissions}}))}
