export type PublicRoute={path:string;title:string;description:string;kind:"page"|"api"|"xml";changeFrequency:"daily"|"weekly"|"monthly";priority:number;operational:boolean};
export const publicRoutes:readonly PublicRoute[]=[
 {path:"/",title:"Tax Practitioner Virtual Office",description:"Public platform overview and authorization posture.",kind:"page",changeFrequency:"weekly",priority:1,operational:false},
 {path:"/platforms",title:"Platforms",description:"Corporate platform directory.",kind:"page",changeFrequency:"weekly",priority:.9,operational:false},
 {path:"/solutions",title:"Solutions",description:"Professional technology and service solutions.",kind:"page",changeFrequency:"weekly",priority:.8,operational:false},
 {path:"/training",title:"Training",description:"Role-based training and career development.",kind:"page",changeFrequency:"weekly",priority:.8,operational:false},
 {path:"/tax-professionals",title:"Tax Professionals",description:"Practitioner services and secure workspace overview.",kind:"page",changeFrequency:"weekly",priority:.8,operational:false},
 {path:"/employers",title:"Employers",description:"Employer, payroll-readiness, and workforce solutions.",kind:"page",changeFrequency:"weekly",priority:.7,operational:false},
 {path:"/students",title:"Students",description:"Student learning and program pathways.",kind:"page",changeFrequency:"weekly",priority:.7,operational:false},
 {path:"/about",title:"About",description:"Corporate mission, standards, and operating principles.",kind:"page",changeFrequency:"monthly",priority:.6,operational:false},
 {path:"/careers",title:"Careers",description:"Career paths across the Ross Tax Pro ecosystem.",kind:"page",changeFrequency:"weekly",priority:.6,operational:false},
 {path:"/support",title:"Support",description:"Customer care and technical support routing.",kind:"page",changeFrequency:"weekly",priority:.7,operational:false},
 {path:"/contact",title:"Contact",description:"Corporate contact and secure inquiry guidance.",kind:"page",changeFrequency:"monthly",priority:.6,operational:false},
 {path:"/universities",title:"Online Universities",description:"Ross Tax Pro University and Ross E-Drive University online campus directory.",kind:"page",changeFrequency:"weekly",priority:.9,operational:false},
 {path:"/universities/ross-tax-pro-university",title:"Ross Tax Pro University",description:"AI-assisted online tax and professional education.",kind:"page",changeFrequency:"weekly",priority:.8,operational:false},
 {path:"/universities/ross-e-drive-university",title:"Ross E-Drive University",description:"AI-assisted online driver education.",kind:"page",changeFrequency:"weekly",priority:.8,operational:false},
 {path:"/universities/academics",title:"Academic Pathways",description:"Proposed degree plans, stackable certificates, diplomas and adult education pathways.",kind:"page",changeFrequency:"weekly",priority:.7,operational:false},
 {path:"/universities/governance",title:"University Governance",description:"Controlled institutional governance and academic policy registry.",kind:"page",changeFrequency:"monthly",priority:.5,operational:false},
 {path:"/api/academics/governance",title:"Governance Registry API",description:"Non-secret document ownership, approval and review-cycle registry.",kind:"api",changeFrequency:"monthly",priority:.1,operational:true},
 {path:"/universities/bookstore",title:"University Bookstore",description:"Course-aligned learning resources and controlled storefront readiness.",kind:"page",changeFrequency:"weekly",priority:.5,operational:false},
 {path:"/api/academics/bookstore",title:"Bookstore Catalog API",description:"Public pre-launch learning-resource catalog and commerce controls.",kind:"api",changeFrequency:"weekly",priority:.1,operational:true},
 {path:"/apply",title:"Academic Application Readiness",description:"Fail-closed program interest and admissions readiness interface.",kind:"page",changeFrequency:"weekly",priority:.6,operational:false},
 {path:"/api/academics/readiness",title:"Academic Readiness API",description:"Non-secret authority, aid, clearinghouse and proctoring gate status.",kind:"api",changeFrequency:"daily",priority:.1,operational:true},
 {path:"/sign-in",title:"Secure Sign In",description:"Clerk-backed staff authentication and SAML entry point.",kind:"page",changeFrequency:"monthly",priority:.3,operational:true},
 {path:"/sign-up",title:"Secure Account Enrollment",description:"Controlled Clerk account enrollment for authorized personnel.",kind:"page",changeFrequency:"monthly",priority:.3,operational:true},
 {path:"/refunds",title:"Refund Command Center",description:"Refund lifecycle and trace workflow overview.",kind:"page",changeFrequency:"weekly",priority:.9,operational:true},
 {path:"/casework",title:"Casework and Interventions",description:"TC 570, TC 810, hardship, and refund trace workflow guidance.",kind:"page",changeFrequency:"weekly",priority:.9,operational:true},
 {path:"/master-file",title:"Master File Reconciliation",description:"Account-module reconciliation controls and event checks.",kind:"page",changeFrequency:"weekly",priority:.9,operational:true},
 {path:"/settings",title:"Platform Control Center",description:"Technology, access-control, and automation registry.",kind:"page",changeFrequency:"monthly",priority:.7,operational:true},
 {path:"/route-registry.xml",title:"XML Route Registry",description:"Machine-readable public route and readiness contract.",kind:"xml",changeFrequency:"weekly",priority:.4,operational:false},
 {path:"/api/health",title:"Health API",description:"Non-secret application and integration configuration status.",kind:"api",changeFrequency:"daily",priority:.2,operational:true},
 {path:"/api/authorizations",title:"Authorization Registry API",description:"Masked source-status and internal readiness registry.",kind:"api",changeFrequency:"weekly",priority:.2,operational:true},
 {path:"/api/security/readiness",title:"Security Readiness API",description:"Non-secret cryptography, redaction, certificate, and policy configuration posture.",kind:"api",changeFrequency:"daily",priority:.2,operational:true},
 {path:"/docs/mcp",title:"MCP Integration",description:"Clerk OAuth protected MCP endpoint documentation and scope model.",kind:"page",changeFrequency:"monthly",priority:.3,operational:true},
 {path:"/api/mcp",title:"MCP Endpoint",description:"Clerk OAuth protected Streamable HTTP MCP endpoint.",kind:"api",changeFrequency:"monthly",priority:.1,operational:true},
 {path:"/support-console",title:"Enterprise Support Console",description:"Authenticated customer-care and IT support operations workspace.",kind:"page",changeFrequency:"weekly",priority:.2,operational:true},
 {path:"/api/agents",title:"AI Agent Directory API",description:"Non-secret persona, authority and human-review registry.",kind:"api",changeFrequency:"weekly",priority:.1,operational:true},
 {path:"/api/workers",title:"Worker Readiness API",description:"Non-secret worker and execution-adapter registry.",kind:"api",changeFrequency:"daily",priority:.1,operational:true},
 {path:"/api/ai/assist",title:"Gemini Advisory API",description:"Authenticated, organization-scoped, redacted advisory AI gateway.",kind:"api",changeFrequency:"monthly",priority:.1,operational:true},
 {path:"/api/universities",title:"University Directory API",description:"Public non-secret university, program, and AI faculty directory.",kind:"api",changeFrequency:"weekly",priority:.1,operational:true},
] as const;
export function absoluteUrl(path:string){const base=(process.env.APP_URL||"http://localhost:3000").replace(/\/$/,"");return `${base}${path}`;}
