export type ServiceDepartment={code:string;name:string;purpose:string;channels:string[];sla:string;restrictions:string[]};
export const serviceDepartments:ServiceDepartment[]=[
 {code:"ADM",name:"Admissions",purpose:"Program information, application readiness, document checklist, and decision communications.",channels:["secure message","scheduled call","accessible video meeting"],sla:"2 business days",restrictions:["No admission promise","No collection of sensitive documents through public forms"]},
 {code:"ENR",name:"Enrollment Services",purpose:"Offer acceptance, registration, enrollment status, add/drop, withdrawal, and orientation.",channels:["student portal","secure message"],sla:"2 business days",restrictions:["Enrollment disabled until program authority is approved"]},
 {code:"REG",name:"Office of the Registrar",purpose:"Academic records, transcript requests, corrections, transfer review, graduation audit, and conferment.",channels:["authenticated request","secure delivery"],sla:"5 business days",restrictions:["Official records require Registrar approval"]},
 {code:"ADV",name:"Academic Advising",purpose:"Degree planning, course sequencing, progress review, academic standing support, and referral.",channels:["appointment","secure message"],sla:"2 business days",restrictions:["Projections are not completion guarantees"]},
 {code:"COUN",name:"Counseling and Student Success",purpose:"Non-clinical student-success counseling, crisis routing, accessibility coordination, and persistence planning.",channels:["appointment","secure referral"],sla:"1 business day",restrictions:["Not emergency or licensed clinical care unless separately staffed"]},
 {code:"SOC",name:"Social Services",purpose:"Needs assessment and consent-based referral to verified community resources.",channels:["private intake","scheduled consultation"],sla:"1 business day",restrictions:["Minimum-necessary data","No diagnosis or benefit guarantee"]},
 {code:"FA",name:"Financial Aid Readiness",purpose:"General FAFSA literacy, eligibility-document checklist, and referral to authorized aid staff.",channels:["secure message","appointment"],sla:"3 business days",restrictions:["No Title IV packaging or award until institutional eligibility is verified"]},
 {code:"BUR",name:"Bursar and Student Billing",purpose:"Published charges, account statements, payment-plan readiness, adjustments, refunds, and reconciliation.",channels:["student account","secure message"],sla:"3 business days",restrictions:["Live payment collection disabled until commerce controls pass"]},
 {code:"ACC",name:"Institutional Accounting",purpose:"Student-ledger control, receivables reconciliation, general-ledger mapping, close, and audit support.",channels:["internal work queue"],sla:"Monthly close calendar",restrictions:["Segregation of duties","No student-facing financial advice"]},
 {code:"ADMIN",name:"University Administration",purpose:"Governance, policy exceptions, complaints, institutional effectiveness, and executive review.",channels:["formal complaint","governance docket"],sla:"Acknowledgement in 3 business days",restrictions:["Material exceptions require documented approval"]},
];
export const intakeTopics=["program_information","application_help","enrollment_status","academic_records","advising","accessibility","student_wellbeing","community_resource_referral","financial_aid_information","billing_question","formal_complaint","technical_support"] as const;
export const intakeFields=["requester_type","first_name","last_name","email","phone_optional","preferred_channel","department","topic","student_id_optional","program_optional","subject","message","urgency","accessibility_accommodation_optional","consent_version"] as const;
export const serviceReadiness={publicInformation:true,secureIntake:false,caseManagement:false,outboundMessaging:false,financialAidProcessing:false,billingTransactions:false,reason:"Production database, consent, retention, staff assignment, secure messaging, and delivery adapters require verification."} as const;
