BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE app_environment AS ENUM ('development','preview','test','production');
CREATE TYPE case_status AS ENUM ('intake','research','waiting','trace','escalation','resolved','closed');
CREATE TYPE task_status AS ENUM ('queued','ready','in_progress','blocked','completed','cancelled','dead_letter');
CREATE TYPE transmission_status AS ENUM ('draft','validated','awaiting_approval','approved','queued','sent','acknowledged','accepted','rejected','quarantined');
CREATE TYPE evidence_status AS ENUM ('provided','verified','disputed','expired','rejected');
CREATE TYPE integration_status AS ENUM ('not_configured','test','active','degraded','suspended','revoked');

CREATE TABLE tenants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),legal_name text NOT NULL,ein_ciphertext bytea,trade_names text[] NOT NULL DEFAULT '{}',status text NOT NULL DEFAULT 'review',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE offices(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),name text NOT NULL,address jsonb NOT NULL DEFAULT '{}',phone text,time_zone text NOT NULL DEFAULT 'America/Chicago',active boolean NOT NULL DEFAULT true,UNIQUE(tenant_id,name));
CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),external_subject text NOT NULL,email_ciphertext bytea,display_name text NOT NULL,status text NOT NULL DEFAULT 'invited',mfa_required boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,external_subject));
CREATE TABLE roles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid REFERENCES tenants(id),code text NOT NULL,description text NOT NULL,system_role boolean NOT NULL DEFAULT false,UNIQUE(tenant_id,code));
CREATE TABLE permissions(code text PRIMARY KEY,description text NOT NULL,risk text NOT NULL CHECK(risk IN ('low','controlled','high')));
CREATE TABLE role_permissions(role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,permission_code text NOT NULL REFERENCES permissions(code),PRIMARY KEY(role_id,permission_code));
CREATE TABLE user_roles(user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE,granted_by uuid REFERENCES users(id),expires_at timestamptz,PRIMARY KEY(user_id,role_id));

CREATE TABLE clients(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),owner_user_id uuid REFERENCES users(id),client_type text NOT NULL CHECK(client_type IN ('individual','business','estate','trust','exempt')),display_name text NOT NULL,tin_last4 char(4),tin_ciphertext bytea,status text NOT NULL DEFAULT 'active',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE authorizations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),client_id uuid REFERENCES clients(id),kind text NOT NULL,scope jsonb NOT NULL DEFAULT '{}',effective_at timestamptz,expires_at timestamptz,status evidence_status NOT NULL DEFAULT 'provided',document_id uuid,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE engagements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),client_id uuid NOT NULL REFERENCES clients(id),service_code text NOT NULL,tax_periods text[] NOT NULL DEFAULT '{}',status text NOT NULL DEFAULT 'draft',signed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE cases(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),client_id uuid NOT NULL REFERENCES clients(id),engagement_id uuid REFERENCES engagements(id),case_number text NOT NULL,title text NOT NULL,case_type text NOT NULL,status case_status NOT NULL DEFAULT 'intake',priority smallint NOT NULL DEFAULT 3 CHECK(priority BETWEEN 1 AND 5),owner_user_id uuid REFERENCES users(id),tax_period text,mft text,next_action text,follow_up_at timestamptz,opened_at timestamptz NOT NULL DEFAULT now(),closed_at timestamptz,UNIQUE(tenant_id,case_number));
CREATE TABLE case_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),case_id uuid NOT NULL REFERENCES cases(id),event_type text NOT NULL,occurred_at timestamptz NOT NULL,recorded_at timestamptz NOT NULL DEFAULT now(),actor_user_id uuid REFERENCES users(id),source_id uuid,payload jsonb NOT NULL DEFAULT '{}',correlation_id uuid NOT NULL DEFAULT gen_random_uuid());
CREATE TABLE transcript_sources(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),client_id uuid NOT NULL REFERENCES clients(id),source_type text NOT NULL,source_hash text NOT NULL,received_at timestamptz NOT NULL DEFAULT now(),tax_period text NOT NULL,mft text,raw_object_key text NOT NULL,UNIQUE(tenant_id,source_hash));
CREATE TABLE transcript_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),source_id uuid NOT NULL REFERENCES transcript_sources(id),case_id uuid REFERENCES cases(id),transaction_code integer NOT NULL CHECK(transaction_code BETWEEN 0 AND 999),transaction_date date NOT NULL,amount numeric(14,2),cycle text,responsibility_code integer,sequence_no integer NOT NULL,raw_line_hash text NOT NULL,UNIQUE(source_id,sequence_no));
CREATE INDEX transcript_event_lookup ON transcript_events(tenant_id,case_id,transaction_date,sequence_no);
CREATE TABLE reconciliation_runs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),case_id uuid NOT NULL REFERENCES cases(id),source_id uuid NOT NULL REFERENCES transcript_sources(id),engine_version text NOT NULL,started_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,result jsonb NOT NULL DEFAULT '{}',reviewer_user_id uuid REFERENCES users(id),reviewed_at timestamptz);

CREATE TABLE documents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),client_id uuid REFERENCES clients(id),case_id uuid REFERENCES cases(id),kind text NOT NULL,object_key text NOT NULL,sha256 text NOT NULL,mime_type text NOT NULL,size_bytes bigint NOT NULL,classification text NOT NULL DEFAULT 'restricted',retention_until date,status evidence_status NOT NULL DEFAULT 'provided',uploaded_by uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,sha256));
ALTER TABLE authorizations ADD CONSTRAINT authorization_document_fk FOREIGN KEY(document_id) REFERENCES documents(id);
CREATE TABLE notices(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),case_id uuid NOT NULL REFERENCES cases(id),notice_code text,notice_date date,response_due date,source_document_id uuid REFERENCES documents(id),status text NOT NULL DEFAULT 'received');
CREATE TABLE contacts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),case_id uuid NOT NULL REFERENCES cases(id),contacted_at timestamptz NOT NULL,channel text NOT NULL,function_name text,representative_reference text,promise_date date,summary text NOT NULL,actor_user_id uuid REFERENCES users(id));

CREATE TABLE tasks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),case_id uuid REFERENCES cases(id),workflow_code text NOT NULL,trigger_code text NOT NULL,title text NOT NULL,status task_status NOT NULL DEFAULT 'queued',assigned_user_id uuid REFERENCES users(id),due_at timestamptz,attempts integer NOT NULL DEFAULT 0,idempotency_key text NOT NULL,blocked_reason text,payload jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,UNIQUE(tenant_id,idempotency_key));
CREATE INDEX task_queue ON tasks(status,due_at) WHERE status IN ('queued','ready','blocked');
CREATE TABLE approvals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),resource_type text NOT NULL,resource_id uuid NOT NULL,requested_by uuid NOT NULL REFERENCES users(id),decision_by uuid REFERENCES users(id),decision text CHECK(decision IN ('approved','rejected')),requested_at timestamptz NOT NULL DEFAULT now(),decided_at timestamptz,reason text,CHECK(decision_by IS NULL OR requested_by<>decision_by));
CREATE TABLE transmissions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),case_id uuid REFERENCES cases(id),system text NOT NULL,environment app_environment NOT NULL,payload_hash text NOT NULL,idempotency_key text NOT NULL,status transmission_status NOT NULL DEFAULT 'draft',prepared_by uuid REFERENCES users(id),approved_by uuid REFERENCES users(id),sent_at timestamptz,acknowledged_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,system,environment,idempotency_key),CHECK(approved_by IS NULL OR prepared_by<>approved_by));
CREATE TABLE acknowledgments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),transmission_id uuid NOT NULL REFERENCES transmissions(id),received_at timestamptz NOT NULL,external_reference text,status text NOT NULL,payload_hash text NOT NULL,raw_object_key text);

CREATE TABLE integrations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),provider text NOT NULL,label text NOT NULL,environment app_environment NOT NULL,status integration_status NOT NULL DEFAULT 'not_configured',secret_reference text,configuration jsonb NOT NULL DEFAULT '{}',last_verified_at timestamptz,UNIQUE(tenant_id,provider,label,environment));
CREATE TABLE webhook_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid REFERENCES tenants(id),provider text NOT NULL,external_event_id text NOT NULL,signature_valid boolean NOT NULL,received_at timestamptz NOT NULL DEFAULT now(),processed_at timestamptz,status task_status NOT NULL DEFAULT 'queued',attempts integer NOT NULL DEFAULT 0,payload_hash text NOT NULL,UNIQUE(provider,external_event_id));
CREATE TABLE audit_events(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,tenant_id uuid,actor_user_id uuid,action text NOT NULL,resource_type text NOT NULL,resource_id text,decision text NOT NULL,reason text,ip_hash text,user_agent_hash text,correlation_id uuid NOT NULL,occurred_at timestamptz NOT NULL DEFAULT now(),details jsonb NOT NULL DEFAULT '{}');
CREATE INDEX audit_tenant_time ON audit_events(tenant_id,occurred_at DESC);
CREATE TABLE outbox(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,tenant_id uuid,topic text NOT NULL,aggregate_type text NOT NULL,aggregate_id text NOT NULL,payload jsonb NOT NULL,idempotency_key text NOT NULL,status task_status NOT NULL DEFAULT 'queued',available_at timestamptz NOT NULL DEFAULT now(),attempts integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(topic,idempotency_key));

ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;ALTER TABLE users ENABLE ROW LEVEL SECURITY;ALTER TABLE clients ENABLE ROW LEVEL SECURITY;ALTER TABLE cases ENABLE ROW LEVEL SECURITY;ALTER TABLE documents ENABLE ROW LEVEL SECURITY;ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;ALTER TABLE transmissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_clients ON clients USING (tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK (tenant_id=current_setting('app.tenant_id',true)::uuid);
CREATE POLICY tenant_isolation_cases ON cases USING (tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK (tenant_id=current_setting('app.tenant_id',true)::uuid);
CREATE POLICY tenant_isolation_documents ON documents USING (tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK (tenant_id=current_setting('app.tenant_id',true)::uuid);
CREATE POLICY tenant_isolation_tasks ON tasks USING (tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK (tenant_id=current_setting('app.tenant_id',true)::uuid);
CREATE POLICY tenant_isolation_transmissions ON transmissions USING (tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK (tenant_id=current_setting('app.tenant_id',true)::uuid);
COMMIT;
