BEGIN;
CREATE TYPE academic_record_status AS ENUM ('draft','active','paused','completed','withdrawn','revoked');
CREATE TYPE academic_decision_status AS ENUM ('proposed','human_review','approved','rejected','appealed');

CREATE TABLE universities(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),code text NOT NULL,name text NOT NULL,delivery_model text NOT NULL DEFAULT '100_percent_online',status academic_record_status NOT NULL DEFAULT 'draft',ai_instruction_enabled boolean NOT NULL DEFAULT false,human_governance_required boolean NOT NULL DEFAULT true,configuration jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,code));
CREATE TABLE university_people(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),university_id uuid NOT NULL REFERENCES universities(id),user_id uuid REFERENCES users(id),person_type text NOT NULL CHECK(person_type IN ('student','employee','human_faculty','human_staff','ai_persona')),title text NOT NULL,status academic_record_status NOT NULL DEFAULT 'active',supervisor_id uuid REFERENCES university_people(id),metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE university_personas(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),university_id uuid NOT NULL REFERENCES universities(id),code text NOT NULL,title text NOT NULL,purpose text NOT NULL,system_prompt_version text NOT NULL,allowed_actions text[] NOT NULL DEFAULT '{}',prohibited_actions text[] NOT NULL DEFAULT '{}',human_approval_actions text[] NOT NULL DEFAULT '{}',status academic_record_status NOT NULL DEFAULT 'draft',UNIQUE(university_id,code));
CREATE TABLE academic_programs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),university_id uuid NOT NULL REFERENCES universities(id),code text NOT NULL,title text NOT NULL,delivery_mode text NOT NULL,planned_hours integer NOT NULL CHECK(planned_hours>0),status academic_record_status NOT NULL DEFAULT 'draft',published_at timestamptz,UNIQUE(university_id,code));
ALTER TABLE courses ADD COLUMN IF NOT EXISTS university_id uuid REFERENCES universities(id);
ALTER TABLE courses ADD COLUMN IF NOT EXISTS program_id uuid REFERENCES academic_programs(id);
CREATE TABLE lessons(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),course_module_id uuid NOT NULL REFERENCES course_modules(id) ON DELETE CASCADE,title text NOT NULL,content_object_key text,estimated_minutes integer NOT NULL CHECK(estimated_minutes>0),ai_faculty_persona_id uuid REFERENCES university_personas(id),human_approved_by uuid REFERENCES users(id),published_at timestamptz,version text NOT NULL,UNIQUE(course_module_id,title,version));
CREATE TABLE learning_progress(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),enrollment_id uuid NOT NULL REFERENCES enrollments(id),lesson_id uuid NOT NULL REFERENCES lessons(id),status academic_record_status NOT NULL DEFAULT 'active',percent_complete numeric(5,2) NOT NULL DEFAULT 0 CHECK(percent_complete BETWEEN 0 AND 100),last_position jsonb NOT NULL DEFAULT '{}',first_opened_at timestamptz,last_activity_at timestamptz,completed_at timestamptz,UNIQUE(enrollment_id,lesson_id));
CREATE TABLE assessments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),course_id uuid NOT NULL REFERENCES courses(id),code text NOT NULL,title text NOT NULL,assessment_type text NOT NULL CHECK(assessment_type IN ('formative','objective','subjective','final')),passing_score numeric(5,2),attempt_limit integer NOT NULL DEFAULT 3,requires_human_review boolean NOT NULL DEFAULT false,status academic_record_status NOT NULL DEFAULT 'draft',UNIQUE(course_id,code));
CREATE TABLE assessment_attempts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),assessment_id uuid NOT NULL REFERENCES assessments(id),enrollment_id uuid NOT NULL REFERENCES enrollments(id),attempt_no integer NOT NULL,answers_object_key text,objective_score numeric(5,2),proposed_score numeric(5,2),final_score numeric(5,2),ai_review jsonb NOT NULL DEFAULT '{}',reviewed_by uuid REFERENCES users(id),submitted_at timestamptz NOT NULL DEFAULT now(),reviewed_at timestamptz,UNIQUE(assessment_id,enrollment_id,attempt_no));
CREATE TABLE academic_decisions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),university_id uuid NOT NULL REFERENCES universities(id),subject_user_id uuid REFERENCES users(id),decision_type text NOT NULL,proposed_by_persona_id uuid REFERENCES university_personas(id),status academic_decision_status NOT NULL DEFAULT 'proposed',facts jsonb NOT NULL DEFAULT '{}',human_decision_by uuid REFERENCES users(id),human_decision_at timestamptz,reason text,appeal_deadline timestamptz,created_at timestamptz NOT NULL DEFAULT now(),CHECK(status NOT IN ('approved','rejected') OR human_decision_by IS NOT NULL));
CREATE TABLE ai_learning_sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),university_id uuid NOT NULL REFERENCES universities(id),user_id uuid NOT NULL REFERENCES users(id),enrollment_id uuid REFERENCES enrollments(id),persona_id uuid NOT NULL REFERENCES university_personas(id),model_reference text NOT NULL,input_hash text NOT NULL,redaction_applied boolean NOT NULL,output_hash text,status text NOT NULL,token_usage jsonb NOT NULL DEFAULT '{}',correlation_id uuid NOT NULL DEFAULT gen_random_uuid(),started_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz);
CREATE TABLE academic_integrity_flags(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),university_id uuid NOT NULL REFERENCES universities(id),assessment_attempt_id uuid REFERENCES assessment_attempts(id),flag_code text NOT NULL,evidence jsonb NOT NULL DEFAULT '{}',status academic_decision_status NOT NULL DEFAULT 'human_review',reviewed_by uuid REFERENCES users(id),reviewed_at timestamptz,resolution text,created_at timestamptz NOT NULL DEFAULT now());

CREATE INDEX university_people_user ON university_people(tenant_id,user_id,status);
CREATE INDEX learning_progress_activity ON learning_progress(tenant_id,last_activity_at) WHERE status='active';
CREATE INDEX academic_decisions_review ON academic_decisions(tenant_id,status,created_at) WHERE status IN ('proposed','human_review','appealed');
CREATE INDEX ai_learning_sessions_audit ON ai_learning_sessions(tenant_id,user_id,started_at DESC);

ALTER TABLE universities ENABLE ROW LEVEL SECURITY; ALTER TABLE university_people ENABLE ROW LEVEL SECURITY; ALTER TABLE university_personas ENABLE ROW LEVEL SECURITY; ALTER TABLE academic_programs ENABLE ROW LEVEL SECURITY; ALTER TABLE lessons ENABLE ROW LEVEL SECURITY; ALTER TABLE learning_progress ENABLE ROW LEVEL SECURITY; ALTER TABLE assessments ENABLE ROW LEVEL SECURITY; ALTER TABLE assessment_attempts ENABLE ROW LEVEL SECURITY; ALTER TABLE academic_decisions ENABLE ROW LEVEL SECURITY; ALTER TABLE ai_learning_sessions ENABLE ROW LEVEL SECURITY; ALTER TABLE academic_integrity_flags ENABLE ROW LEVEL SECURITY;
CREATE POLICY university_tenant_isolation ON universities USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);
CREATE POLICY university_people_tenant_isolation ON university_people USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);
CREATE POLICY learning_progress_tenant_isolation ON learning_progress USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);
CREATE POLICY academic_decision_tenant_isolation ON academic_decisions USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);
CREATE POLICY ai_learning_session_tenant_isolation ON ai_learning_sessions USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);
COMMIT;
