BEGIN;
CREATE TABLE IF NOT EXISTS curriculum_standards(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text NOT NULL UNIQUE,title text NOT NULL,jurisdiction text NOT NULL,authority text NOT NULL,source_url text NOT NULL,effective_date date,reviewed_at timestamptz,review_status text NOT NULL DEFAULT 'pending');
CREATE TABLE IF NOT EXISTS program_versions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),program_id uuid NOT NULL REFERENCES academic_programs(id),catalog_year text NOT NULL,award_status text NOT NULL CHECK(award_status IN ('proposed','non_degree','preparatory','authorized','suspended')),total_credits numeric(6,2),effective_at timestamptz,approved_by uuid REFERENCES users(id),approved_at timestamptz,disclosures jsonb NOT NULL DEFAULT '{}',UNIQUE(program_id,catalog_year));
CREATE TABLE IF NOT EXISTS course_resources(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),course_id uuid NOT NULL REFERENCES courses(id),resource_type text NOT NULL CHECK(resource_type IN ('coursebook','primary_source','oer','dataset','case','laboratory','media','accessibility_alternative')),title text NOT NULL,creator text,edition text,source_url text,license text NOT NULL,provenance_verified boolean NOT NULL DEFAULT false,accessibility_status text NOT NULL DEFAULT 'pending',last_reviewed_at timestamptz,next_review_at timestamptz,UNIQUE(course_id,title,edition));
CREATE TABLE IF NOT EXISTS course_outcomes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),course_id uuid NOT NULL REFERENCES courses(id),outcome_code text NOT NULL,description text NOT NULL,cognitive_level text NOT NULL,evidence_method text NOT NULL,standard_id uuid REFERENCES curriculum_standards(id),UNIQUE(course_id,outcome_code));
CREATE TABLE IF NOT EXISTS curriculum_publication_reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),program_version_id uuid NOT NULL REFERENCES program_versions(id),review_type text NOT NULL CHECK(review_type IN ('academic','legal','authorization','accreditation','accessibility','consumer_disclosure','library','financial')),status text NOT NULL CHECK(status IN ('pending','approved','rejected','expired')),reviewed_by uuid REFERENCES users(id),reviewed_at timestamptz,evidence_object_key text,expires_at timestamptz,notes text);
CREATE INDEX IF NOT EXISTS course_resources_review_due ON course_resources(tenant_id,next_review_at) WHERE provenance_verified;
CREATE INDEX IF NOT EXISTS curriculum_publication_gate ON curriculum_publication_reviews(tenant_id,program_version_id,status);
ALTER TABLE program_versions ENABLE ROW LEVEL SECURITY; ALTER TABLE course_resources ENABLE ROW LEVEL SECURITY; ALTER TABLE course_outcomes ENABLE ROW LEVEL SECURITY; ALTER TABLE curriculum_publication_reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY program_versions_tenant ON program_versions USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);
CREATE POLICY course_resources_tenant ON course_resources USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);
CREATE POLICY course_outcomes_tenant ON course_outcomes USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);
CREATE POLICY curriculum_publication_reviews_tenant ON curriculum_publication_reviews USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);
INSERT INTO curriculum_standards(code,title,jurisdiction,authority,source_url,review_status) VALUES
('TX-TCC','Texas Core Curriculum','Texas','Texas Higher Education Coordinating Board','https://www.highered.texas.gov/new-program-development/texas-core-curriculum/','verified'),
('TX-BUS-FOS','Business Administration Field of Study','Texas','Texas Higher Education Coordinating Board','https://reportcenter.highered.texas.gov/agency-publication/miscellaneous/business-administration-field-of-study-revised-apr-2023/','verified'),
('TX-HOME','Texas Alternative Schooling / Home School','Texas','Texas Education Agency','https://tea.texas.gov/families-and-students/finding-school-your-child/alternative-schooling','verified'),
('TX-FHSP','Foundation High School Program','Texas','Texas Education Agency','https://tea.texas.gov/educators/graduation-information/foundation-high-school-program','verified'),
('TX-CHSE','Texas Certificate of High School Equivalency / GED','Texas','Texas Education Agency','https://tea.texas.gov/student-readiness-and-high-school/texas-certificate-high-school-equivalency-ged','verified')
ON CONFLICT(code) DO UPDATE SET title=excluded.title,source_url=excluded.source_url;
COMMIT;
