BEGIN;
CREATE TABLE learning_resources(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),sku text NOT NULL,title text NOT NULL,format text NOT NULL,edition text,accessibility_status text NOT NULL CHECK(accessibility_status IN ('pending','validated','exception_review')),rights_status text NOT NULL CHECK(rights_status IN ('pending','licensed','open','expired','blocked')),license_terms jsonb NOT NULL DEFAULT '{}',price_cents integer NOT NULL DEFAULT 0 CHECK(price_cents>=0),currency char(3) NOT NULL DEFAULT 'USD',publication_status text NOT NULL CHECK(publication_status IN ('draft','review','published','retired')),version integer NOT NULL DEFAULT 1,UNIQUE(tenant_id,sku));
CREATE TABLE course_resource_mappings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),course_id uuid NOT NULL,resource_id uuid NOT NULL REFERENCES learning_resources(id),requirement text NOT NULL CHECK(requirement IN ('required','recommended','optional')),effective_term text NOT NULL,approved_by uuid REFERENCES users(id),UNIQUE(tenant_id,course_id,resource_id,effective_term));
CREATE TABLE resource_offers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),resource_id uuid NOT NULL REFERENCES learning_resources(id),offer_type text NOT NULL CHECK(offer_type IN ('included','oer','publisher_direct','rental','print_on_demand')),provider text NOT NULL,external_uri text,price_cents integer CHECK(price_cents>=0),status text NOT NULL CHECK(status IN ('draft','active','paused','expired')),verified_at timestamptz);
CREATE TABLE resource_entitlements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),resource_id uuid NOT NULL REFERENCES learning_resources(id),student_user_id uuid NOT NULL REFERENCES users(id),source text NOT NULL,starts_at timestamptz NOT NULL,expires_at timestamptz,revoked_at timestamptz,UNIQUE(resource_id,student_user_id,source));
CREATE INDEX resource_course_idx ON course_resource_mappings(tenant_id,course_id,effective_term);CREATE INDEX entitlement_student_idx ON resource_entitlements(tenant_id,student_user_id,expires_at);
ALTER TABLE learning_resources ENABLE ROW LEVEL SECURITY;ALTER TABLE course_resource_mappings ENABLE ROW LEVEL SECURITY;ALTER TABLE resource_offers ENABLE ROW LEVEL SECURITY;ALTER TABLE resource_entitlements ENABLE ROW LEVEL SECURITY;
CREATE POLICY learning_resources_tenant ON learning_resources USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);CREATE POLICY course_resource_mappings_tenant ON course_resource_mappings USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);CREATE POLICY resource_offers_tenant ON resource_offers USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);CREATE POLICY resource_entitlements_tenant ON resource_entitlements USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);
COMMIT;
