from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, KeepTogether

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'output/pdf/Endi-Aguilar-Audit-Grade-Onboarding-Training-Packet.pdf'
NAVY=colors.HexColor('#071A32'); NAVY2=colors.HexColor('#102A4A'); GOLD=colors.HexColor('#BC9650'); CREAM=colors.HexColor('#F4EEE3'); SILVER=colors.HexColor('#D6D9DE'); INK=colors.HexColor('#152238'); MUTED=colors.HexColor('#657184'); WHITE=colors.HexColor('#FFFDF8')
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='CoverTitle',fontName='Helvetica-Bold',fontSize=27,leading=31,textColor=WHITE,spaceAfter=14))
styles.add(ParagraphStyle(name='CoverSub',fontName='Helvetica',fontSize=11,leading=17,textColor=colors.HexColor('#D7DFE9')))
styles.add(ParagraphStyle(name='Section',fontName='Helvetica-Bold',fontSize=21,leading=26,textColor=NAVY,spaceAfter=12))
styles.add(ParagraphStyle(name='H2x',fontName='Helvetica-Bold',fontSize=13,leading=17,textColor=NAVY2,spaceBefore=9,spaceAfter=6))
styles.add(ParagraphStyle(name='Bodyx',fontName='Helvetica',fontSize=9,leading=13.5,textColor=INK,spaceAfter=6))
styles.add(ParagraphStyle(name='Smallx',fontName='Helvetica',fontSize=7.4,leading=10.5,textColor=MUTED,spaceAfter=4))
styles.add(ParagraphStyle(name='Callout',fontName='Helvetica-Bold',fontSize=9,leading=13,textColor=NAVY,backColor=CREAM,borderColor=GOLD,borderWidth=1,borderPadding=9,spaceBefore=8,spaceAfter=10))

def P(text,style='Bodyx'): return Paragraph(text.replace('&','&amp;'),styles[style])
def bullet(text): return Paragraph('• '+text.replace('&','&amp;'),styles['Bodyx'])
def fields(rows,widths=(2.2*inch,4.3*inch)):
 data=[[P(a,'Smallx'),P(b or '__________________________________________________','Bodyx')] for a,b in rows]
 t=Table(data,colWidths=widths,repeatRows=0);t.setStyle(TableStyle([('BACKGROUND',(0,0),(0,-1),CREAM),('BOX',(0,0),(-1,-1),.5,SILVER),('INNERGRID',(0,0),(-1,-1),.35,SILVER),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),8),('RIGHTPADDING',(0,0),(-1,-1),8),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7)]));return t
def matrix(headers,rows,widths):
 data=[[P(x,'Smallx') for x in headers]]+[[P(str(x),'Smallx') for x in row] for row in rows]
 t=Table(data,colWidths=widths,repeatRows=1);t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),NAVY),('TEXTCOLOR',(0,0),(-1,0),WHITE),('BOX',(0,0),(-1,-1),.5,SILVER),('INNERGRID',(0,0),(-1,-1),.35,SILVER),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),5),('RIGHTPADDING',(0,0),(-1,-1),5),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));return t
def section(story,num,title,subtitle=None):
 story.append(PageBreak());story.append(P(f'{num:02d} / CONTROLLED SECTION','Smallx'));story.append(P(title,'Section'))
 if subtitle: story.append(P(subtitle,'Callout'))
def header_footer(c,doc):
 c.saveState();w,h=LETTER;c.setFillColor(NAVY);c.rect(0,h-34,w,34,fill=1,stroke=0);c.setFillColor(GOLD);c.rect(0,h-36,w,2,fill=1,stroke=0);c.setFont('Helvetica-Bold',7);c.setFillColor(WHITE);c.drawString(42,h-22,'ROSS TAX PRO SOFTWARE CO.  |  PEOPLE + PRACTICE OPERATIONS');c.setStrokeColor(GOLD);c.line(42,38,w-42,38);c.setFillColor(MUTED);c.setFont('Helvetica',7);c.drawString(42,25,'CONFIDENTIAL WORKFORCE DOCUMENT  |  CONTROLLED COPY');c.drawRightString(w-42,25,f'PAGE {doc.page}');c.restoreState()

story=[]
# Cover
story.append(Spacer(1,1.25*inch));cover=Table([[P('ROSS TAX PRO<br/>SOFTWARE CO.','CoverTitle')],[P('ENDI AGUILAR<br/><br/><b>Audit-Grade Onboarding, Employment Terms, Orientation & Role-Based Career Development Packet</b><br/><br/>Tax Practitioner Services • Tax Office Management • Refund Casework • TC 570 / TC 810 Research & Intervention Support','CoverSub')]],colWidths=[6.5*inch]);cover.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),NAVY),('BOX',(0,0),(-1,-1),2,GOLD),('LEFTPADDING',(0,0),(-1,-1),34),('RIGHTPADDING',(0,0),(-1,-1),34),('TOPPADDING',(0,0),(-1,-1),28),('BOTTOMPADDING',(0,0),(-1,-1),28)]));story.append(cover);story.append(Spacer(1,.35*inch));story.append(P('Prepared: September 5, 2026  |  Version 1.0  |  Status: Draft for authorized employer and employee completion','Smallx'));story.append(P('Important: This packet is an operational template and training instrument. It is not legal advice, does not replace required federal or state forms, and does not itself establish compensation, exempt status, agency authority, or a guarantee of continued employment.','Callout'))

section(story,1,'Document Control & Seeded Employee Profile')
story.append(fields([('Employee / Participant','Endi Aguilar'),('Employer / Trade Name','Ross Tax Pro Software Co.'),('Employing Legal Entity','TO BE VERIFIED AND COMPLETED BY AUTHORIZED OFFICER'),('Work Location / State','________________________'),('Position at Appointment','________________________'),('Supervisor','________________________'),('Start Date','________________________'),('90-Day Review Date','________________________'),('Employment Classification','Employee / Contractor determination pending authorized review'),('Document Owner','Human Resources / Compliance'),('Version','1.0 - September 5, 2026')]))
story.append(P('Control rule: do not execute the employment agreement until the legal employing entity, work state, classification, compensation, and authorized signatory have been completed and reviewed.','Callout'))

section(story,2,'Indexed Table of Contents')
toc=['Document Control & Seeded Profile','Table of Contents','Welcome, Mission & What We Stand For','Terms of Employment and 90-Day Introductory Period','Compensation Election and Commission Addendum','Privacy, Confidentiality and Taxpayer Data','Corporate Uniform, Appearance and Workplace Conduct','Required HR Onboarding Forms Index','Self-Paced Orientation Curriculum','Role-Based Tax Practitioner Curriculum','Tax Office Management Track','TC 570 / TC 810 Research Specialist Track','Refund Trace and Release Intervention Track','LMS Onboarding Script','Career Progression and Pay-Grade Matrix','Data Entry Fields and Case Logic','Andrea AI Assistance and Responsible Use','Performance, Quality Assurance and Audit Controls','90-Day Milestone Plan','Acknowledgments and Signature Pages','Official References and Revision Control']
story.append(matrix(['Index','Controlled section'],[(f'{i:02d}',x) for i,x in enumerate(toc,1)],[.65*inch,5.85*inch]))

section(story,3,'Welcome, Mission & What We Stand For')
story.append(P('Welcome, Endi Aguilar. Ross Tax Pro Software Co. is building a disciplined virtual-office culture where professional judgment, taxpayer dignity, data protection, accurate work, accountable service, and continuous learning come before volume.'))
story.append(P('Mission','H2x'));story.append(P('Deliver secure, evidence-centered tax practitioner services and software-supported casework that help clients understand and navigate tax administration without exaggeration, pressure, discrimination, or unsupported promises.'))
story.append(P('Operating values','H2x'))
for x in ['Integrity: case records say exactly what is known, unknown, prepared, submitted, received, and resolved.','Security: taxpayer information is accessed only for assigned work and protected through approved systems.','Competence: practitioners work only within training, authorization, and professional limits.','Accountability: corrections are documented; conflicts and incidents are escalated promptly.','Service: clients receive respectful communication, realistic expectations, and clear next steps.','Growth: advancement follows demonstrated quality, security discipline, credentials, and leadership readiness.']:story.append(bullet(x))

section(story,4,'Terms of Employment and 90-Day Introductory Period','At-will language and an introductory period do not erase rights under applicable law or create a guaranteed term. Authorized counsel should review this section for the employee work state.')
for h,txt in [('Appointment','The employer appoints Endi Aguilar to the position entered in the Employee Profile, subject to completion of required verification, agreements, training, access approval, and any lawful conditions of employment.'),('At-Will Relationship','Unless a written agreement signed by an authorized corporate officer expressly states otherwise, employment is intended to be at will to the fullest extent permitted by applicable law. Either party may end employment at any time, with or without advance notice or cause, subject to applicable law. No manager may alter this status orally.'),('Introductory Period','The first 90 calendar days are an introductory assessment period. Continued employment during or after that period is not guaranteed. The employer may extend training, restrict access, reassign duties, or end employment consistent with law and policy.'),('Performance Conditions','Evaluation includes attendance, timely training, data-security behavior, documentation accuracy, client communication, escalation judgment, production quality, and compliance with authorization boundaries.'),('Conflicts and Outside Activity','Employee must disclose outside tax-preparation, bookkeeping, financial-product, software, or client-service activities that may create a conflict, data risk, divided loyalty, or misuse of employer resources.'),('Policies and Changes','Policies are operational guidance and are not a contract unless expressly identified and signed as such. The employer may revise prospective procedures, subject to law and required notice.')]:story.append(P(h,'H2x'));story.append(P(txt))

section(story,5,'Compensation Election & Commission Addendum','No pay term is effective until every field is completed, reviewed for applicable wage-and-hour rules, and signed by an authorized officer.')
story.append(fields([('Pay Basis','□ Hourly  □ Salary  □ Commission plus hourly/base  □ Other'),('Training Rate','$____________ per hour'),('Regular Base Rate / Salary','$________________________'),('Commission Formula','__________________________________________________'),('Employee Share','________ %'),('Firm Share','________ %'),('Eligible Revenue Definition','__________________________________________________'),('Chargeback / Reversal Rules','__________________________________________________'),('Pay Frequency','□ Semi-monthly  □ Biweekly  □ Other __________'),('Overtime Classification','□ Nonexempt  □ Exempt - basis reviewed and documented'),('Effective Date','________________________'),('Approving Officer','________________________')]))
story.append(P('Commission pay does not by itself remove minimum-wage, overtime, timekeeping, or recordkeeping obligations. The regular rate and overtime treatment must be determined under applicable law. Unauthorized deductions, retroactive formula changes, and off-the-clock work are prohibited.','Callout'))

section(story,6,'Privacy, Confidentiality & Taxpayer Data Agreement')
for x in ['Access taxpayer data only for assigned work, valid authorization, and a permissible business purpose.','Do not copy data to personal email, devices, drives, screenshots, messaging applications, or unapproved AI services.','Use assigned accounts, MFA, approved devices, encryption, secure disposal, and clean-desk controls.','Immediately report loss, misdirection, phishing, malware, suspicious access, or disclosure. Do not investigate secretly.','Return and delete employer information as directed at separation, subject to preservation and legal-hold requirements.','Client information remains protected after employment ends.']:story.append(bullet(x))
story.append(P('Tax-return information use and disclosure must comply with IRC sections 6713 and 7216 and applicable consent rules. The firm must maintain a written information security program and safeguards appropriate to its risk profile. Publication 4557 and the FTC Safeguards Rule are incorporated as compliance references, not as a substitute for legal review.'))
story.append(fields([('Employee Initials - Confidentiality','________'),('Employee Initials - Security','________'),('Employee Initials - Incident Reporting','________'),('Security Training Date','________________________')]))

section(story,7,'Corporate Uniform, Appearance & Workplace Conduct')
for x in ['Approved palette: navy, gold, silver, tan, cream, white, and restrained black trim.','Business professional or approved branded business casual attire is required for client-facing work.','Identification badges must be worn where issued and never shared.','Clothing and backgrounds must be clean, non-distracting, and suitable for video appointments.','No apparel or conduct may imply IRS employment, government endorsement, credentials not held, or guaranteed outcomes.','Reasonable religious, disability, pregnancy, gender-expression, and other lawful accommodations will be considered through HR.']:story.append(bullet(x))
story.append(P('Workplace conduct requires professionalism, nondiscrimination, anti-harassment, respectful communication, accurate timekeeping, conflicts disclosure, and immediate escalation of threats or safety concerns.'))

section(story,8,'Required HR Onboarding Forms Index')
rows=[('Identity and work authorization','Form I-9 completed through authorized process; retain separately'),('Federal withholding','Current Form W-4'),('State/local withholding','As applicable to work state/locality'),('Direct deposit','Bank authorization through secure payroll channel'),('Emergency contact','Internal HR record'),('Confidentiality/privacy','Section 6 acknowledgment'),('Technology use','Account, device, acceptable-use acknowledgment'),('Compensation','Completed Section 5 addendum'),('Conflict disclosure','Outside practice and related-party disclosure'),('Credentials','PTIN and professional credentials where role requires'),('Training','Assigned LMS curriculum and due dates'),('Policy receipt','Section 20 signatures')]
story.append(matrix(['Record','Completion requirement'],rows,[2.15*inch,4.35*inch]));story.append(P('Do not place Form I-9 supporting documents, bank information, full SSNs, or identity documents in this general packet. Store them in their designated restricted systems.','Callout'))

section(story,9,'Self-Paced Orientation Curriculum')
rows=[('Phase 1 - Welcome and security','6 hrs','Mission, conduct, privacy, MFA, phishing, incident response'),('Phase 2 - Platform and records','8 hrs','Navigation, RBAC, case notes, document vault, audit events'),('Phase 3 - Tax practice foundations','18 hrs','Due diligence, intake, research, review, communication'),('Phase 4 - Refund casework','16 hrs','Transcripts, freeze indicators, traces, referrals, follow-up'),('Phase 5 - Supervised simulations','20 hrs','Complete sandbox cases with documented review'),('Phase 6 - Role certification','8 hrs','Knowledge check, observed task, remediation, approval')]
story.append(matrix(['Phase','Duration','Measurable outcome'],rows,[2.2*inch,.7*inch,3.6*inch]));story.append(P('Estimated total: 76 hours. Duration is a planning estimate, not a waiver of compensable-time requirements. Required employee training must be handled consistently with applicable wage-and-hour rules.'))

section(story,10,'Role-Based Tax Practitioner Curriculum')
for h,txt in [('Intake and Authorization','Confirm identity, engagement, consent, representative authority, tax period, service scope, and conflicts.'),('Return Preparation','Apply current law and forms; document source evidence, elections, estimates, due diligence, review findings, and taxpayer approval.'),('Transcripts and Notices','Preserve source records, normalize dates and transaction codes, distinguish facts from inference, and connect each action to controlling guidance.'),('Quality Review','Reperform material calculations, resolve discrepancies, verify names/TIN data in restricted systems, validate signatures and e-file authorization, and record reviewer disposition.'),('Client Communication','Explain status without promising results; give dated next steps, missing-document lists, responsible party, and follow-up date.')]:story.append(P(h,'H2x'));story.append(P(txt))
story.append(fields([('Knowledge Assessment','Score: ______ / 100'),('Observed Case Simulation','□ Pass  □ Remediation'),('Reviewer','________________________'),('Role Activation Date','________________________')]))

section(story,11,'Tax Office Management Track')
for x in ['Daily opening: staffing, system status, deadlines, unresolved acknowledgments, security alerts, and client escalations.','Work allocation: competency, authorization, capacity, conflicts, and separation of duties.','Quality: sampling, error taxonomy, correction ownership, trend review, and retraining.','Revenue: approved pricing, earned-revenue rules, refunds/chargebacks, payroll handoff, and reconciliation.','People: coaching, schedule control, documented performance, accommodations, and escalation to HR.','Closing: reconcile transmissions, lock physical information, close queues, preserve evidence, and confirm backups/alerts.']:story.append(bullet(x))
story.append(fields([('Manager Candidate','Endi Aguilar'),('Prerequisite Role','________________________'),('Leadership Simulation','________________________'),('Approval Status','□ Not started  □ In progress  □ Approved')]))

section(story,12,'TC 570 / TC 810 Research Specialist Track','These transaction codes can indicate a stopped or frozen refund. Staff cannot input, reverse, or release IRS transaction codes unless separately authorized by the IRS within an official IRS function.')
rows=[('TC 570','Additional-liability or compliance hold indicator','Research source, related notices, pending activity, and controlling function; monitor authoritative resolution.'),('TC 571/572','Potential release/reversal event','Evaluate the complete module and pending activity; do not assume refund issuance.'),('TC 810','Refund freeze indicator','Capture date and available responsibility information; identify controlling IRS function; prepare permitted evidence/referral.'),('TC 811','Freeze-release transaction','Confirm posting and complete module status; document what remains before representing resolution.'),('TC 846/840','Refund issue event','Validate date, amount, method, offsets, and trace eligibility if non-receipt is reported.')]
story.append(matrix(['Event','Meaning boundary','Required workflow'],rows,[.75*inch,1.75*inch,4*inch]));story.append(P('Specialist title means trained caseworker. It does not imply government authority or a guaranteed “reversal.” Marketing, client notes, and invoices must use accurate wording.','Callout'))

section(story,13,'Refund Trace & Release Intervention Track')
steps=['Verify authorization, taxpayer identity, tax period, and source transcript.','Confirm that a refund was issued and record TC 846/840 date, amount, and payment method.','Confirm non-receipt facts, address/direct-deposit details, joint-return facts, and prior trace activity.','Apply current IRM 21.4.2 timing and Form 3911/oral-statement procedures.','Record IRS/BFS/TCIS references, contact dates, promise dates, and disposition.','For hardship, document immediate adverse impact and evaluate current TAS criteria.','Close only with authoritative resolution evidence or documented transfer/withdrawal.']
for i,x in enumerate(steps,1):story.append(P(f'<b>{i}. {x}</b>'))
story.append(P('“Intervention submitted” is not “refund released.” “Release requested” is not “release approved.” Every system status must preserve that distinction.','Callout'))

section(story,14,'LMS Onboarding Script')
script='''Welcome, Endi Aguilar, to Ross Tax Pro Software Co. This orientation introduces the standards that protect our clients, our team, and the integrity of every case. Begin by confirming your assigned identity and MFA. Never share credentials. Work only inside your assigned tenant, role, and case queue. Each record must distinguish verified facts from assumptions and drafted actions from completed actions. If a transcript shows TC 570 or TC 810, pause, research the controlling facts, and follow the approved workflow. Do not promise a release. Andrea may help organize facts and sources, but a qualified human remains accountable for material tax conclusions and submissions. If anything looks wrong, stop and escalate. Precision is part of service.'''
story.append(P(script));story.append(fields([('Employee Viewed','□ Yes'),('Completion Date','________________________'),('Knowledge Check','________ %'),('Facilitator / LMS Record','________________________')]))

section(story,15,'Career Progression & Pay-Grade Matrix')
rows=[('Tax Practitioner in Training','Orientation + supervised simulations','Restricted; no independent submission','Grade / rate assigned by HR'),('Tax Practitioner I','Core assessment + security approval','Assigned returns and case tasks','Grade / commission addendum required'),('Tax Practitioner II','Quality threshold + advanced cases','Expanded forms/case complexity','Grade / commission addendum required'),('Refund Casework Specialist','Transcript + trace certification','Research and prepare interventions','Specialty differential if approved'),('Senior Reviewer','Review certification + quality history','Independent quality review','Grade assigned by HR'),('Tax Office Manager','Leadership simulation + compliance approval','Staff, queues, quality, escalation','Salary/base/bonus plan if approved')]
story.append(matrix(['Role','Advancement milestone','Authority boundary','Compensation control'],rows,[1.35*inch,1.7*inch,1.7*inch,1.75*inch]));story.append(P('No automatic promotion, commission percentage, or salary is promised by this matrix. Advancement depends on business need, lawful classification, performance, credentials, security conduct, and written approval.'))

section(story,16,'Data Entry Fields & Case Logic')
rows=[('Identity','tenant, client ID, masked TIN, name control, DOB/entity type','Exact tenant match; restrict sensitive values'),('Authority','engagement, Form 2848/8821 status, consent, scope, expiration','Block work outside scope or after expiration'),('Return','tax year, form, filing status, received/accepted dates','Preserve source and version'),('Transcript event','code, date, amount, cycle, source hash','Sort chronologically; never mutate source'),('Case','type, owner, status, priority, deadline, next action','Every open case requires owner and follow-up'),('Contact','time, channel, function, representative, reference, promise','Append-only audit event'),('Intervention','basis, evidence, draft, approver, submission proof','Separate preparation, approval, and submission'),('Outcome','authoritative event, source, date, reviewer','No elapsed-time closure')]
story.append(matrix(['Domain','Required fields','Validation logic'],rows,[1.05*inch,2.8*inch,2.65*inch]))

section(story,17,'Andrea AI Assistance & Responsible Use')
story.append(P('Andrea is an evidence-centered assistant for organizing facts, identifying discrepancies, locating current official guidance, drafting communications, producing checklists, and proposing reviewable next actions.'))
for x in ['Use restricted case context for taxpayer data; never place full TINs or credentials in general chat.','Request sources and revision dates for unstable tax, employment, or security rules.','Require outputs to separate provided facts, verified facts, uncertainty, analysis, actions, approval gate, and confidence.','Human review is mandatory for filings, amendments, transmissions, hardship referrals, identity-theft determinations, and material client advice.','Tool results and authoritative records control; fluent language is not proof.']:story.append(bullet(x))
story.append(P('Approved prompt: “Using only the authorized case facts and current official sources, identify verified events, unresolved discrepancies, applicable procedure, missing evidence, permitted next actions, approval requirements, and confidence. Do not predict a refund date or represent a requested action as completed.”','Callout'))

section(story,18,'Performance, Quality Assurance & Audit Controls')
rows=[('Security and privacy','No critical violation; timely reporting','Weekly during introductory period'),('Training completion','100% assigned modules by due date','Weekly'),('Documentation quality','Accurate, sourced, complete, timely','Sampled cases'),('Tax accuracy','Meets reviewer threshold; corrections completed','Each supervised case'),('Client service','Professional, clear, no unsupported promises','Call/message sampling'),('Productivity','Role-adjusted completed work without quality sacrifice','After training baseline'),('Escalation judgment','Stops and routes high-risk matters correctly','Observed continuously')]
story.append(matrix(['Dimension','Standard','Evidence'],rows,[1.55*inch,3.25*inch,1.7*inch]));story.append(P('Corrective action may include coaching, access restriction, remediation, reassignment, written warning, or separation, applied consistently with law and policy.'))

section(story,19,'90-Day Milestone Plan')
rows=[('Days 1-7','HR forms, security, accounts, mission, policies','No production access until approved'),('Days 8-30','Core LMS, sandbox intake and recordkeeping','30-day review and remediation plan'),('Days 31-60','Supervised casework and transcript simulations','Quality sample and specialty readiness'),('Days 61-89','Role-level production under assigned review','Final evidence portfolio'),('Day 90','Formal review, access decision, development plan','Continue, extend training, reassign, or separate')]
story.append(matrix(['Period','Milestone','Gate'],rows,[1.05*inch,3.5*inch,1.95*inch]));story.append(fields([('30-Day Rating','________________________'),('60-Day Rating','________________________'),('90-Day Decision','________________________'),('Development Priority','________________________'),('Manager Signature / Date','________________________')]))

section(story,20,'Acknowledgments & Signature Pages')
ack='I acknowledge receipt of this packet and understand that I must ask questions about any requirement I do not understand. I agree to follow approved security, confidentiality, technology, conduct, documentation, and escalation requirements. I understand that training titles do not grant IRS authority; employment and compensation terms are effective only when completed and signed by an authorized officer; and this packet does not guarantee a particular term, promotion, commission, salary, client volume, refund result, or continued employment.'
story.append(P(ack));story.append(Spacer(1,10));story.append(fields([('Employee','Endi Aguilar'),('Employee Signature','__________________________________________________'),('Date','________________________'),('Authorized Employer Representative','__________________________________________________'),('Title','________________________'),('Signature','__________________________________________________'),('Date','________________________'),('HR / Witness','__________________________________________________'),('Date','________________________')]))
story.append(P('Separate required signatures may apply to the compensation addendum, confidentiality agreement, technology-use policy, arbitration agreement (if any), and state-specific notices. Obtain legal review before use.','Callout'))

section(story,21,'Official References & Revision Control')
refs=[('IRS Publication 4557','Safeguarding Taxpayer Data: A Guide for Your Business','https://www.irs.gov/pub/irs-pdf/p4557.pdf'),('IRS Publication 1345','Handbook for Authorized IRS e-file Providers','https://www.irs.gov/pub/irs-pdf/p1345.pdf'),('IRS Publication 4163','Modernized e-File Information for Authorized Providers','https://www.irs.gov/pub/irs-pdf/p4163.pdf'),('IRM 21.4.1','Refund Research','https://www.irs.gov/irm/part21/irm_21-004-001r'),('IRM 21.4.2','Refund Trace and Limited Payability','https://www.irs.gov/irm/part21/irm_21-004-002r'),('IRM 21.5.6','Freeze Codes','https://www.irs.gov/irm/part21/irm_21-005-006r'),('FTC','Safeguards Rule','https://www.ftc.gov/business-guidance/privacy-security/gramm-leach-bliley-act'),('U.S. DOL','Wages and the Fair Labor Standards Act','https://www.dol.gov/agencies/whd/flsa')]
story.append(matrix(['Authority','Subject','Official location'],refs,[1.45*inch,2.15*inch,2.9*inch]));story.append(Spacer(1,12));story.append(fields([('Reviewed By','________________________'),('Legal/HR Review Date','________________________'),('Next Annual Review','________________________'),('Supersedes Version','________________________'),('Change Summary','__________________________________________________')]))

doc=SimpleDocTemplate(str(OUT),pagesize=LETTER,leftMargin=.58*inch,rightMargin=.58*inch,topMargin=.62*inch,bottomMargin=.58*inch,title='Endi Aguilar Audit-Grade Onboarding and Training Packet',author='Ross Tax Pro Software Co.',subject='Controlled workforce onboarding and tax practitioner training packet')
doc.build(story,onFirstPage=header_footer,onLaterPages=header_footer)
print(OUT)
